### ISSUE TITLE
A new and pathetic "icon" issue barely worth even worrying about

### ISSUE THREAD

**Issue by primal-buddhist** [getting-things-gnome/gtg#904] opened 2022-06-07 08:36 UTC
1. I edit a tag
2. I click on the icon
3. I select, say, a person with a stethoscope 
4. And a generic head appears
5. Or I select a red heart with a bandage
6. And a black heart with no bandage appears

Some icons, maybe 70%, are good, but many don't work - flags for eg, or people with trades. 

I am on Fedora WS 36, GTG 0.6

**Comment by nekohayo** [comment] 2022-06-07 13:46
Maybe something is going on with the GTK emoji selector where your mouse clicks don't match the icon underneath? I've seen it happen elsewhere, especially on laggy social media websites with their own emoji picker, that if you move the mouse you have to wait for the preselection to arrive under the icon before clicking it... but I haven't experienced that problem with the GTK emoji picker.

**Comment by primal-buddhist** [comment] 2022-06-07 13:56
Even if I use the keyboard to select it happens

It doesn't pick the one next door, it sort of substitutes one quite like it.  

In the case of "people with trades" it just selects a head like the head but without any of the tools or stethoscopes. It selects the right gender but the jumper will change colour. Or there will be a monochrome version.

My gut feeling is that there are two sets, mapped to each other, but I don't know enough about the underlying system to say how that is possible. So on the right there is the "recently used emoji" list and I can see that it is the green jumpered man but on the left, in the gtg spot, you can see the orange jumpered man. Like the library in GTG is mapped to the library in the picker but with a similar but not identical set.

**Comment by Neui** [comment] 2022-06-07 14:57
Some emojis are created by combining other emojis. For flags for example, they are just two special characters, it is up to the system/font to for example make [regional indicator symbol](https://en.wikipedia.org/wiki/Regional_Indicator_Symbol)s "DE" to 🇩🇪.

It seems that GTG is chopping off any additional emojis. Looking a bit it seems the [`max-length`-property of the invisible Gtk.Entry](https://github.com/getting-things-gnome/gtg/blob/v0.6/GTG/gtk/data/tag_editor.ui#L98=) seems to be the cause; Upping the limit (at least via the [GTK inspector](https://docs.gtk.org/gtk3/running.html#interactive-debugging)) makes at least the flag work (and applies correctly as expected).

**Comment by kocio-pl** [comment] 2022-06-12 00:42
I guess this might be the same as #817.

**Comment by diegogangl** [comment] 2022-06-19 23:06
This is fixed in the gtk4 port (#894). It will take quite a while to hit master though
![Screenshot from 2022-06-19 20-05-38](https://user-images.githubusercontent.com/264829/174503615-debfd84b-5691-42a5-96ae-6f59a4ee3b82.png)

**Closed** 2024-02-19 23:25 UTC
Labels: priority:low, needinfo
