### ISSUE TITLE
How to remove "old" tags

### ISSUE THREAD

**Issue by primal-buddhist** [getting-things-gnome/gtg#905] opened 2022-06-10 07:55 UTC
Maybe there is a way, otherwise a nice to have enhancement,

I have switched from a random mix of upper and lower case for tags to all lower case (Money -> money) and would like to remove all previous upper case tags from the suggested tags when ctrl-t ing tasks. There are also a few misspelled old tags that pop up there too.

Is there a hack for this in a data file right now?

best

J

**Comment by nekohayo** [comment] 2022-06-10 17:43
In terms of implementation, this is essentially a duplicate of #560, and in terms of objectives a duplicate of #605 and #307; for the time being, the workaround is to edit the gtg tasks XML file with your favorite text editor while GTG is not running, and you can find the list of tags near the top of the file. You will find a _lot_ of duplicates to remove! If you want to be extra careful, you can search for their hashes/IDs to see if they are used by any tasks elsewhere in the file. It would of course be much better if GTG avoided creating those gazillion duplicates, and provided a UI to manage all tags (#560).

**Closed by nekohayo** 2022-06-10 17:43 UTC
Labels: duplicate, question
