### ISSUE TITLE
Version 0.5 sometimes breaks (goes into an inconsistent state due to tracebacks) and cannot show proper search results or filtered "Open" tasks

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#726] opened 2021-11-09 03:12 UTC
I have been experiencing this issue for months, I don't know if it will still affect the git version after @diegogangl's refactoring changes, and I don't know exactly how to trigger it, but in case this can somehow be useful, here is a first traceback that I managed to catch now, after some extended normal use of the app (with various searches and tags switching etc).:

```
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/GTG/gtk/browser/main_window.py", line 1109, in on_start_for_next_day_2
    self.update_start_to_next_day(2)
  File "/app/lib/python3.8/site-packages/GTG/gtk/browser/main_window.py", line 1091, in update_start_to_next_day
    task.set_start_date(next_day)
  File "/app/lib/python3.8/site-packages/GTG/core/task.py", line 577, in set_start_date
    self.sync()
  File "/app/lib/python3.8/site-packages/GTG/core/task.py", line 760, in sync
    self.modified()
  File "/app/lib/python3.8/site-packages/liblarch/treenode.py", line 52, in modified
    self.tree.modify_node(self.node_id, priority=priority)
  File "/app/lib/python3.8/site-packages/liblarch/tree.py", line 89, in modify_node
    self._queue.push(self._modify_node, node_id, priority=priority)
  File "/app/lib/python3.8/site-packages/liblarch/processqueue.py", line 67, in push
    func(*element[1:])
  File "/app/lib/python3.8/site-packages/liblarch/tree.py", line 261, in _modify_node
    self._callback('node-modified', node_id)
  File "/app/lib/python3.8/site-packages/liblarch/tree.py", line 79, in _callback
    func(node_id)
  File "/app/lib/python3.8/site-packages/liblarch/filteredtree.py", line 130, in __external_modify
    return self.__update_node(node_id, direction="both")
  File "/app/lib/python3.8/site-packages/liblarch/filteredtree.py", line 181, in __update_node
    self.__update_node(parent_id, direction="up")
  File "/app/lib/python3.8/site-packages/liblarch/filteredtree.py", line 209, in __update_node
    self.send_add_tree(node_id, parent_id)
  File "/app/lib/python3.8/site-packages/liblarch/filteredtree.py", line 269, in send_add_tree
    self.callback('added', node_id, path)
  File "/app/lib/python3.8/site-packages/liblarch/filteredtree.py", line 114, in callback
    func(param)
TypeError: argument path: Expected Gtk.TreePath, but got tuple
```

...and then, the user-visible symptom is that, once this has happened, when you are in the "Actionable" view mode, if you open the searchbar and search for something to filter something, and then switch to "Open" tasks mode with the search filter still active, then you get the wrong results shown (it just shows everything) alongside this new traceback:

```
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/GTG/gtk/browser/main_window.py", line 1353, in on_pane_switch
    self.reapply_filter(current_pane)
  File "/app/lib/python3.8/site-packages/GTG/gtk/browser/main_window.py", line 1329, in reapply_filter
    self._try_filter_by_query(search, refresh=is_last)
  File "/app/lib/python3.8/site-packages/GTG/gtk/browser/main_window.py", line 442, in _try_filter_by_query
    vtree.apply_filter(SEARCH_TAG, parse_search_query(query),
  File "/app/lib/python3.8/site-packages/liblarch/viewtree.py", line 285, in apply_filter
    self.__ft.apply_filter(filter_name, parameters, reset, refresh)
  File "/app/lib/python3.8/site-packages/liblarch/filteredtree.py", line 629, in apply_filter
    self.refilter()
  File "/app/lib/python3.8/site-packages/liblarch/filteredtree.py", line 321, in refilter
    self.send_remove_tree(node_id, self.root_id)
  File "/app/lib/python3.8/site-packages/liblarch/filteredtree.py", line 290, in send_remove_tree
    self.callback('deleted', node_id, path)
  File "/app/lib/python3.8/site-packages/liblarch/filteredtree.py", line 126, in callback
    func(node_id, path)
  File "/app/lib/python3.8/site-packages/liblarch/viewtree.py", line 119, in __emit
    func(node_id, path)
  File "/app/lib/python3.8/site-packages/liblarch_gtk/treemodel.py", line 156, in remove_task
    raise Exception(
Exception: Trying to remove node 7587c443-a5c9-4cb8-aa08-f0d750885a30 with no iterator
```

**Comment by diegogangl** [comment] 2021-11-09 12:55
The new core is still far from being plugged in (hasn't even landed). This is a classic deep-liblarch bug

**Comment by Neui** [comment] 2021-11-13 01:32
My analysis:

In `filteredtree.py:114`, `func(param)` is used to call `func` with parameter `param`. The message `TypeError: argument path: Expected Gtk.TreePath, but got tuple` seems so come from PyGObject, very likely `func` is a `PyGObject` function (one of the `Gtk.Tree*` functions to be more precise).
Also note that this is only called when an "runonce"-Callback for an node has been set, and an node is added to the view.

I traced usages and found `liblarch_gtk/__init__.py:270` as the only usage. The passed parameter `collapsing_method` can either be `self.expand_one_row` (which is a python method) OR `None`, which sets it to `self.collapse_row`, which is a `Gtk.TreeView` function!
Since the passed parameter is a liblarch path object, this is already very wrong.

But how to trigger it? I couldn't reproduce yet, but the only place this function with `collapsing_method=None` is called is in `main_browser.py:539` (inside `restore_collapsed_tasks`).
This is called on initial config reading, some preferences changes, and `refresh_all_views` in `main_browser.py`, which is called by the refresh timer thing (which we can "trigger" by using the dev console: `browser.refresh_all_views(1)`).

In `collapse_node` the condition to do `queue_action` (to register such event) is either to have a non-existing task that was previously collapsed (`iter is None`, because you've deleted it for example) OR `self.basetreemodel.get_value(iter, 0)` does not return the expected `node_id`.
I'd guess the latter part wasn't equal, but this would imply the requested iterator for that `node_id` doesn't point to the correct row, which is very weird...
(Not immediately going the deleted route since it is hard to create a task with the same ID, I guess. Or maybe .... I'll look later)

(Line numbers approximate on current git master)

**Comment by Neui** [comment] 2021-11-13 16:09
Reproduction steps inside GTG:

1. Create 3 subtasks of each other, so it looks like this:
    * Toplevel Task
        * Sub Task
            * Sub sub Task
2. Give the top-level task a tag, other are tagless
3. Collapse all tasks
5. Select "tasks without tags" on the sidebar (task is now expanded again, which looks like another bug)
6. Open dev console and type: `browser.refresh_all_tasks(1)` (or wait for the refresh timer to kick in). The visible task will now be collapsed.
7. Click "all tasks" in the sidebar
8. Error pops up (in the git version in that error handler)

**Comment by diegogangl** [comment] 2021-11-15 17:29
Fixed in liblarch

**Closed by diegogangl** 2021-11-15 17:29 UTC
Labels: bug, needinfo
