### ISSUE TITLE
fatal_internal_error-at_startup

### ISSUE THREAD

**Issue by ignito17** [getting-things-gnome/gtg#985] opened 2023-09-13 05:00 UTC
**Context:** Activation

```python-traceback
None```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.2, PyGObject 3.42.2
* Linux-6.4.14-200.fc38.x86_64-x86_64-with-glibc2.33

**Comment by nekohayo** [comment] 2023-11-27 15:40
This bug report is not detailed enough to be actionable.  Considering it a duplicate of issue #845 or #961...

**Closed by nekohayo** 2023-11-27 15:40 UTC
Labels: duplicate, invalid
