### ISSUE TITLE
How to not show Tasks' pop-up window when GTG launches

### ISSUE THREAD

**Issue by haudelard-ua** [getting-things-gnome/gtg#1104] opened 2024-05-23 14:48 UTC
I've looked everywhere but couldn't find a solution. Is it possible and if so how to do it please ?

Thanks

**Comment by SqAtx** [comment] 2024-05-25 21:19
Do you mean that all your open tasks pop up when you open GTG and you have to close them one by one?

In my experience, this happens when GTG wasn't stopped properly. So I make sure to close GTG before shutting off my computer, for example. But yes, we should look into fixing this.

**Comment by haudelard-ua** [comment] 2024-05-27 07:43
Yes it is indeed that. So when I shutdown my computer without shutting down GTG, when I restart it all tasks pop up.

Thank you for your reply

**Comment by nekohayo** [comment] 2024-05-30 21:21
Yup that's a bug.

Duplicate of #713

**Closed by nekohayo** 2024-05-30 21:21 UTC
Labels: bug, duplicate
