### ISSUE TITLE
GTG0.3.1 crashes upon closing on Ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by redflag33** [getting-things-gnome/gtg#202] opened 2016-10-16 05:54 UTC
Error message:

It looks like an error has occurred.
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(_targs, *_kargs)
  File "/usr/share/gtg/GTG/plugins/bugzilla/notification.py", line 64, in uinit_pynotify
    pynotify.uninit()
NameError: global name 'pynotify' is not defined

**Comment by nekohayo** [comment] 2019-12-12 03:16
Duplicate of #196

**Closed by nekohayo** 2019-12-12 03:16 UTC
