### ISSUE TITLE
"Due" Value doesn't update unless GTG is restarted

### ISSUE THREAD

**Issue by RatGit** [getting-things-gnome/gtg#86] opened 2015-02-01 22:50 UTC
I often hibernate my laptop instead of shutting it down. Unfortunately GTG doesn't track the current date/time and update the "Due" column value in the task list view. So far the only way I've found to do this is to restart GTG.

**Comment by nekohayo** [comment] 2019-12-11 22:37
Presuming this is the same issue I had in 0.3.1 and earlier, the workaround is to click some other UI element such as the calendar dropdown arrow of the due date widget, or hitting the Tab key to defocus that widget.

Potential implementation tips for whoever may be investigating/fixing this:

* If not already the case, this should probably use a GTK event signal to check/validate the syntax of the due date's field (same for start date) and then save it only when a valid value is entered.
* One could also make the changes effective when the task's contents view is focused.

**Comment by diegogangl** [comment] 2020-02-14 15:17
This is a duplicate of #214

**Closed by diegogangl** 2020-02-14 15:17 UTC
Labels: bug, low-hanging-fruit, priority:low
