### ISSUE TITLE
Internal error when trying to add a new sync service

### ISSUE THREAD

**Issue by samyak-jain** [getting-things-gnome/gtg#896] opened 2022-05-15 11:01 UTC
To reproduce:
- Go to the option button in the top right
- Click on Synchonization
- After the dialog opens, click on the plus button

We then get an error. Here's the stack trace I got:
```
**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/__init__.py", line 231, in on_add_button
    self.add_panel.refresh_backends()
  File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/addpanel.py", line 141, in refresh_backends
    self.combo_types.refresh()
  File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/backendscombo.py", line 81, in refresh
    pixbuf = self.dialog.get_pixbuf_from_icon_name(module.Backend.get_icon(), 16)
  File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/__init__.py", line 121, in get_pixbuf_from_icon_name
    return Gtk.IconTheme.get_default().load_icon(name, height, 0)
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Icon 'applications-internet' not present in theme Adwaita (0)
```

**Software versions:**
* Getting Things GNOME! 0.6.0
* CPython 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
* GTK 3.24.33, GLib 2.72.0
* PyGLib 3.42.1, PyGObject 3.42.1
* Linux-5.17.5-zen1-1-zen-x86_64-with-glibc2.35
```

**Comment by CoderThomasB** [comment] 2022-05-22 21:29
I'm getting the same error while using the flatpack of the app.

**Comment by julianfairfax** [comment] 2022-05-27 17:22
I have this same bug

**Comment by diegogangl** [comment] 2022-05-28 01:33
Sorry guys, we got auto-updated on flathub and the new SDK started triggering the error. I've reverted the commit and pushed an update. This should be fixed by now

**Comment by julianfairfax** [comment] 2022-05-28 22:46
> Sorry guys, we got auto-updated on flathub and the new SDK started triggering the error. I've reverted the commit and pushed an update. This should be fixed by now

It worked!

**Comment by idle5** [comment] 2022-06-05 21:45
I'm getting an issue when trying to enable Hamster time tracking integration after going to options -> plugins . Recently downloaded from flathub :( Thanks for any help in advance. 

```
**Context:** Global generic exception
python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: org.freedesktop.DBus.Error.NameHasNoOwner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/plugins.py", line 216, in on_plugin_toggle
    self.pengine.activate_plugins([plugin])
  File "/app/lib/python3.9/site-packages/GTG/core/plugins/engine.py", line 202, in activate_plugins
    plugin.instance.activate(api)
  File "/app/lib/python3.9/site-packages/GTG/plugins/hamster/hamster.py", line 155, in activate
    self.hamster = dbus.SessionBus().get_object('org.gnome.Hamster',
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/app/lib/python3.9/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.2.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.1, PyGObject 3.42.1
* Linux-5.15.0-35-generic-x86_64-with-glibc2.33`

**Comment by CoderThomasB** [comment] 2022-06-05 23:07
It's working for me as well!

**Comment by samyak-jain** [comment] 2022-06-26 15:54
I am still facing this issue since I don't use flathub. Looks like it is a duplicate of https://github.com/getting-things-gnome/gtg/issues/846. Feel free to close this if we want to track this there instead.

**Comment by nekohayo** [comment] 2022-07-10 14:09
Yup let's consider it a duplicate of 846, then.

**Closed by nekohayo** 2022-07-10 14:09 UTC
Labels: duplicate, packaging
