### ISSUE TITLE
Editing, Finishing or discarding a subtask doesn't automatically update the parent task window when it's open

### ISSUE THREAD

**Issue by jasaldivara** [getting-things-gnome/gtg#38] opened 2014-07-28 16:28 UTC
When I have a task's view window open and made changes wich affect that task, the changes aren't automatically updated on the task window.

Examples of changes that aren't automatically updated on the task window:
Finnishing, discarding and renaming a subtask.

If i want to see the changes applied in the task window, i need to close and reopen that window.

System info:
Version: Getting Things GNOME! 0.3.1
Fedora 20.

**Comment by nekohayo** [comment] 2019-12-11 21:31
I haven't tested if the git version still is affected by this (I will presume so); if it is, this is indeed something that would be nice to fix, but I'm not sure how hard it would be. It might be easy (in which case this could be tagged "low-hanging-fruit") or ridiculously hard and error-prone...

**Comment by nekohayo** [comment] 2020-05-29 17:17
While it doesn't address the root cause from a purely theoretical standpoint, the fix for issue 326 resolves this in practice, so closing for the 0.4 release.

**Closed by nekohayo** 2020-05-29 17:17 UTC
Labels: bug, duplicate, priority:medium, reproducible-in-git
