### ISSUE TITLE
Tab completion for tags

### ISSUE THREAD

**Issue by mweisshaupt1988** [getting-things-gnome/gtg#884] opened 2022-04-21 11:32 UTC
I use tags a lot and would appreciate if gtg was able to tab complete them.

For example with the following tag "MyFancyAndTooLongTag" it would be nice if I just needed to write "@My" and then a list with possible completions would pop up.

**Comment by diegogangl** [comment] 2022-04-22 22:18
This would be really cool, and it's doable now that we are using GtkSourceView. Closing as duplicate of #374

**Closed by diegogangl** 2022-04-22 22:18 UTC
