### ISSUE TITLE
Remove alphabetical sorting and list new tasks below each other

### ISSUE THREAD

**Issue by digitalethics** [getting-things-gnome/gtg#422] opened 2020-07-14 10:48 UTC
Currently, new tasks are sorted alphabetically. I think this is not very intuitive as users typically expect tasks to be added below each other. For me this is a _make-it or break-it_ feature as it severely limits usability.

**Comment by nekohayo** [comment] 2020-07-14 15:26
Duplicate of #70

**Closed by nekohayo** 2020-07-14 15:26 UTC
Labels: duplicate, enhancement
