### ISSUE TITLE
gtg v0.6 installed from Flathub crash on startup

### ISSUE THREAD

**Issue by Nebdaker** [getting-things-gnome/gtg#962] opened 2023-03-18 17:41 UTC
**This is a context :**
**Context:** Activation

```python-traceback
None```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.2, PyGObject 3.42.2
* Linux-5.10.0-21-amd64-x86_64-with-glibc2.33


**And this is what I got when I ran it in debug mode**
2023-03-18 18:29:49,580 - ERROR - application:do_activate:153 - Exception during activation
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: org.freedesktop.DBus.Error.NameHasNoOwner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 148, in do_activate
    self.init_shared()
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 229, in init_shared
    self.init_plugin_engine()
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 255, in init_plugin_engine
    self.plugin_engine.activate_plugins()
  File "/app/lib/python3.9/site-packages/GTG/core/plugins/engine.py", line 202, in activate_plugins
    plugin.instance.activate(api)
  File "/app/lib/python3.9/site-packages/GTG/plugins/hamster/hamster.py", line 155, in activate
    self.hamster = dbus.SessionBus().get_object('org.gnome.Hamster',
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/app/lib/python3.9/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
2023-03-18 18:29:49,750 - INFO - backend_caldav:_do_periodic_import:137 - Running periodic import
2023-03-18 18:29:55,959 - INFO - errorhandler:handle_response:163 - Going to exit because either of fatal error or user choice

**Comment by nekohayo** [comment] 2024-02-26 16:17
Can anyone reproduce this on the latest git `master` version, or was this indirectly fixed by the big refactoring?

**Comment by nekohayo** [comment] 2024-02-26 16:50
Oooh, actually this is a duplicate of issue #683!

**Closed by nekohayo** 2024-02-26 16:50 UTC
Labels: bug, duplicate, priority:critical, packaging

**Comment by nekohayo** [comment] 2024-02-26 17:00
Duplicate of #683
