### ISSUE TITLE
issue with updating days left coloum

### ISSUE THREAD

**Issue by cactiCode** [getting-things-gnome/gtg#213] opened 2017-09-19 09:56 UTC
im currently running Fedora 26 and there is an issue with updating the days left coloum in the program, (have to go and edit each task to update the days left in that tab), please fix this ass soon as possible. thanks anyway :D

**Comment by nekohayo** [comment] 2019-12-12 03:43
Duplicate of #214 I suspect.

**Closed by nekohayo** 2019-12-12 03:43 UTC
