### ISSUE TITLE
When selecting a saved search, the search query gets inserted into the quick-add entry, created tasks inherit the search name

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#590] opened 2021-03-19 20:41 UTC
Here's a minor and subtle bug (can't believe I hadn't noticed it before), certainly a legacy from the 0.3.x GUI. It happens in both 0.4 and the git version:

if you click a tag in the sidebar, the quick-add GtkEntry stays empty (if it was empty). However, if you click a saved search in the sidebar, the contents of the quick-add entry get replaced by the search string. Probably some old code that doesn't need to be there anymore...

**Comment by nekohayo** [comment] 2021-03-25 22:45
Okay this is a little bit nastier than I thought... not only does it pollute the quick-add entry, but if you create a new task while you are inside that saved search's view, using "Ctrl+n", the newly created task will:
* have the search query inserted into its body when the task editor shows up...
* and _even_ if you deleted the cruft above from the task editor, and replace by clean tags, then when you shut down and restart GTG... it will turn out that it actually silently kept the fake tag associated with the task all along; on startup you'll see that search query/name "without the spaces" showing up as if it was a tag, and the tasks are still tagged with it (at least from what I saw with 0.4):

![Screenshot from 2021-03-25 18-41-42](https://user-images.githubusercontent.com/479401/112552985-11520500-8d9a-11eb-95d9-066d2a63b9f7.png)

**Comment by zeddo123** [comment] 2021-03-28 17:30
Hey @nekohayo,
I wasn't able to reproduce the second part of the bug on the master branch. It might have been fixed indirectly?

**Comment by nekohayo** [comment] 2021-03-30 00:39
OK so this turns out to be a three-part bug then:
1. fixed by your branch: the fact that the search shows up in the quick add bar
2. not fixed by your branch (unfortunately): the search query being inserted into newly created tasks' body when the task editor shows up
3. seemingly not occurring in your branch or master (only in 0.4, so probably obsolete, as you've observed): ~~"even if you deleted the cruft above from the task editor [from part 2], when you shut down and restart GTG... it have been silently kept and associated with the task, and on startup you'll see that search query/name "without the spaces" showing up as if it was a tag"~~

**Comment by nekohayo** [comment] 2021-03-30 00:58
Number 2 is almost certainly due to the fact that saved searches and tags are internally the same thing, and in my case here I've been using search queries that search for specific tags, i.e.: `contrats !or @accounting !or @taxes` and so, since GTG inherits the selected tag from the sidebar when you Ctrl+n to create a new task, it looks at that selected search query and goes "well look at that, it has `@` symbols, it's clearly some tags!" and then tags the hell out of it.

**Comment by zeddo123** [comment] 2021-03-30 18:50
This is some confusing bug :D

>2. not fixed by your branch yet (unfortunately): the search query being inserted into newly created tasks' body when the task editor shows up (as it inherits whatever is selected in the sidebar)

Were you able to reproduce it on my branch (because I can't)? or is it obsolete?

**Comment by nekohayo** [comment] 2021-03-31 15:06
> Were you able to reproduce no.2 on my branch (because I can't)? or is it obsolete?

If you rebased your branch on master with diego's fixes (or we simply cherry-pick your commit) that would mean both 1 and 2 are fixed, so I guess your branch would be ready to merge if you agree (I haven't retested the whole combo and probably won't until the week-end though, but your fix seemed straightforward and to do what it was meant to do the last time I tested)

**Closed** 2021-03-31 18:49 UTC
Labels: bug, low-hanging-fruit, priority:medium, reproducible-in-git
