### ISSUE TITLE
Error when enable plugin "Not Today"

### ISSUE THREAD

**Issue by tkdchen** [getting-things-gnome/gtg#120] opened 2015-06-04 01:11 UTC
```
Traceback (most recent call last):
  File "/home/cqi/projects/gtg/GTG/gtk/plugins.py", line 261, in on_plugin_toggle
    self.pengine.activate_plugins([plugin])
  File "/home/cqi/projects/gtg/GTG/core/plugins/engine.py", line 220, in activate_plugins
    plugin.instance.activate(api)
  File "/home/cqi/projects/gtg/GTG/plugins/not_today/not_today.py", line 32, in activate
    self._init_gtk()
  File "/home/cqi/projects/gtg/GTG/plugins/not_today/not_today.py", line 62, in _init_gtk
    self.plugin_api.add_toolbar_item(self.tb_button)
  File "/home/cqi/projects/gtg/GTG/core/plugins/api.py", line 169, in add_toolbar_item
    self.__toolbar.insert(widget, -1)
AttributeError: 'NoneType' object has no attribute 'insert'

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/cqi/projects/gtg/GTG/gtk/crashhandler.py", line 122, in _replacement_excepthook
    res = show_error_window(tb, add_apport_button=add_apport_button)
  File "/home/cqi/projects/gtg/GTG/gtk/crashhandler.py", line 219, in show_error_window
    expander = Gtk.expander_new_with_mnemonic(_("_Details"))
  File "/usr/lib64/python3.4/site-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib64/python3.4/site-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'expander_new_with_mnemonic'

Original exception was:
Traceback (most recent call last):
  File "/home/cqi/projects/gtg/GTG/gtk/plugins.py", line 261, in on_plugin_toggle
    self.pengine.activate_plugins([plugin])
  File "/home/cqi/projects/gtg/GTG/core/plugins/engine.py", line 220, in activate_plugins
    plugin.instance.activate(api)
  File "/home/cqi/projects/gtg/GTG/plugins/not_today/not_today.py", line 32, in activate
    self._init_gtk()
  File "/home/cqi/projects/gtg/GTG/plugins/not_today/not_today.py", line 62, in _init_gtk
    self.plugin_api.add_toolbar_item(self.tb_button)
  File "/home/cqi/projects/gtg/GTG/core/plugins/api.py", line 169, in add_toolbar_item
    self.__toolbar.insert(widget, -1)
AttributeError: 'NoneType' object has no attribute 'insert'
```

**Comment by izidormatusov** [comment] 2015-06-04 11:58
Working as intended. @jakubbrindza's work temporarily broke plugin API and it is going to be fixed at the later stage of the summer. I believe the rest of plugins might be broken in similar fashion.

@jakubbrindza : we need to provide way for plugins how to extend the new UI

**Comment by nekohayo** [comment] 2019-12-11 23:15
This particular plugin needs to be turned into a core feature, maybe @ploum will be interested by it, otherwise up for grabs I guess.

**Comment by diegogangl** [comment] 2019-12-16 00:02
This is technically in core, if you right-click a task you can set the due date for tomorrow. It would be nice to have something more powerful, like a re-schedule popup that lets you select the next 7 days/next week/next month or no date.

**Comment by nekohayo** [comment] 2020-04-03 04:30
AFAIK the feature was implemented in core now, right? But the plugin still needs to be killed, because it's still available there in the list of plugins and tracebacks if yout ry to enable it.

**Closed** 2020-04-05 23:18 UTC
Labels: bug, low-hanging-fruit, priority:critical, reproducible-in-git
