### ISSUE TITLE
Exception at startup - 'Datastore' object has no attribute 'load_tag_tree'

### ISSUE THREAD

**Issue by piio** [getting-things-gnome/gtg#995] opened 2024-02-22 08:14 UTC
Hi,

After updating to newest version v0.6-367-g66f91627, during startup I see following error :

```
2024-02-22 09:12:43,617 - INFO - backend_caldav:_do_periodic_import:137 - Running periodic import
Missing command "pdftk"
```

```python-traceback
Exception in thread Thread-1 (__backend_startup):
Traceback (most recent call last):
  File "/usr/lib64/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "~/.archive/src/gtg/.local_build/install/lib/python3.12/site-packages/GTG/core/datastore.py", line 578, in __backend_startup
    backend.initialize()
  File "~/.archive/src/gtg/.local_build/install/lib/python3.12/site-packages/GTG/backends/backend_localfile.py", line 130, in initialize
    self.datastore.load_tag_tree(self.tag_tree)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Datastore' object has no attribute 'load_tag_tree'
```

Btw. great job!

**Comment by diegogangl** [comment] 2024-04-13 21:58
Indeed, the localfile backend was removed (since those bits are handled by the Datastore itself now). Closing since the bug isn't reproducible anymore

**Closed by diegogangl** 2024-04-13 21:58 UTC
Labels: needinfo, reproducible-in-git, regression
