### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'nodeValue'

### ISSUE THREAD

**Issue by sametmax** [getting-things-gnome/gtg#145] opened 2015-06-16 13:47 UTC
When I click on one of my task, I get :

```
Traceback (most recent call last):
  File "/usr/share/gtg/GTG/gtk/editor/taskviewserial.py", line 158, in unserialize
    success = self.parsexml(content_buf, ite, element.firstChild)
  File "/usr/share/gtg/GTG/gtk/editor/taskviewserial.py", line 207, in parsexml
    text = n.firstChild.nodeValue
AttributeError: 'NoneType' object has no attribute 'nodeValue'
`

Most probably the xml has been corrupted. I had several weird behaviours in gtg and my guess is that sometime, it doesn't produce a proper xml.

**Comment by izidormatusov** [comment] 2015-06-16 19:58
Do you mind to either run our [anonymize_task_file.py](https://github.com/getting-things-gnome/gtg/blob/master/scripts/anonymize_task_file.py) script or share your task xml? (It can be send to my gmail address so it's not shared with everybody)

**Comment by izidormatusov** [comment] 2015-06-18 07:18
I believe this is duplicate of #45

**Closed by izidormatusov** 2015-06-18 07:18 UTC
Labels: needinfo

**Comment by sametmax** [comment] 2015-06-19 13:27
Ok, just in case, here is the offending xml node :

```    <task id="5fd54847-9b1f-4a5c-9676-09e7f8b4d522" status="Active" tags="@cetrimestre,@projet" uuid="1391bb3d-9c60-4f71-96b4-17f72dad5016">
        <title>Participer à l'open source</title>
        <modified>2015-06-15T20:23:15</modified>
        <donedate>2015-06-15</donedate>
        <subtask>81600584-7747-4f2e-893c-e25478c1755e</subtask>
        <subtask>11f0195f-8f31-4e97-b5e9-3e7dacfe64c6</subtask>
        <subtask>85e2bc41-c15f-4cc7-a0d9-dcc8ba02afe9</subtask>
        <subtask>4919340d-f7cd-4681-b9be-b09ba11e5bf4</subtask>
        <content>&lt;tag&gt;@projet &lt;/tag&gt;
 <subtask>81600584-7747-4f2e-893c-e25478c1755e</subtask>
 <subtask>11f0195f-8f31-4e97-b5e9-3e7dacfe64c6</subtask>
 <subtask>85e2bc41-c15f-4cc7-a0d9-dcc8ba02afe9</subtask>
 &lt;/tag&gt; proposer sur python-idea de mettre une mention de pip sur tout les pages de pypi qui ont une build générique</content>
        <task-remote-ids/>
    </task>
```

**Comment by nekohayo** [comment] 2020-02-25 19:52
@sametmax I devised some ways to trigger the bug in #45; you may be interested in checking if those are the same for you, and if they still happen in the git version of GTG (if you're feeling motivated to test it out :)
