### ISSUE TITLE
Internal error when adding syncronisation

### ISSUE THREAD

**Issue by Sonipes** [getting-things-gnome/gtg#934] opened 2022-10-16 19:19 UTC
When trying to add a syncronisation (settings -> synconisation -> "+") this error appers:

**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/__init__.py", line 231, in on_add_button
    self.add_panel.refresh_backends()
  File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/addpanel.py", line 141, in refresh_backends
    self.combo_types.refresh()
  File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/backendscombo.py", line 81, in refresh
    pixbuf = self.dialog.get_pixbuf_from_icon_name(module.Backend.get_icon(), 16)
  File "/usr/lib/python3.10/site-packages/GTG/gtk/backends/__init__.py", line 121, in get_pixbuf_from_icon_name
    return Gtk.IconTheme.get_default().load_icon(name, height, 0)
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Symbol »applications-internet« nicht im Thema Adwaita vorhanden (0)
```

**Software versions:**
* Getting Things GNOME! v0.6-71-g25dfa55e
* CPython 3.10.8 (main, Oct 11 2022, 20:04:56) [GCC 12.2.0]
* GTK 3.24.34, GLib 2.74.0
* PyGLib 3.42.2, PyGObject 3.42.2
* Linux-6.0.1-arch2-1-x86_64-with-glibc2.36

**Comment by Neui** [comment] 2022-10-16 19:37
Duplicate of #846

**Closed** 2023-01-07 20:53 UTC
Labels: duplicate

**Comment by necessarily-equal** [comment] 2024-05-19 19:48
Hello, this issue with several others have been marked as duplicates of #846, but issue #846 doesn't seem to be publicly accessible (404 for me at least).

What's the status on that issue? What solutions were found if any?

This issue seems to be present in NixOS as well: https://github.com/NixOS/nixpkgs/issues/312977
