### ISSUE TITLE
Feature Request: Use alternative Icon picker widget for tag editor

### ISSUE THREAD

**Issue by BeatLink** [getting-things-gnome/gtg#524] opened 2020-12-08 03:20 UTC
This library implements an icon picker that grants access to all the icons on the user's system. This would not only give the users more choice but be easier to maintain as well.

https://github.com/Tomha/python-gtk-themed-icon-chooser

**Comment by nekohayo** [comment] 2020-12-10 19:07
I'd say this is a duplicate of issue #85 and PR #508.

**Closed by nekohayo** 2020-12-10 19:07 UTC
