### ISSUE TITLE
Activating the Hamster plugin without Hamster present (or missing permissions in Flatpak) will cause tracebacks on startup, crashing / preventing GTG's future launches with `DBus.Error.NameHasNoOwner` and `DBus.Error.ServiceUnknown`

### ISSUE THREAD

**Issue by jorgeecardona** [getting-things-gnome/gtg#683] opened 2021-06-07 08:34 UTC
Hi, I have installed GTG 0.5 via flapak, I am getting the following error the first time I run the app with `flatpak run org.gnome.GTG`

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/app/lib/python3.8/site-packages/dbus/bus.py", line 359, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.8/site-packages/dbus/connection.py", line 650, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: org.freedesktop.DBus.Error.NameHasNoOwner
```

During handling of the above exception, another exception occurred:

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 123, in do_activate
    self.init_shared()
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 162, in init_shared
    self.init_plugin_engine()
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 188, in init_plugin_engine
    self.plugin_engine.activate_plugins()
  File "/app/lib/python3.8/site-packages/GTG/core/plugins/engine.py", line 201, in activate_plugins
    plugin.instance.activate(api)
  File "/app/lib/python3.8/site-packages/GTG/plugins/hamster/hamster.py", line 155, in activate
    self.hamster = dbus.SessionBus().get_object('org.gnome.Hamster',
  File "/app/lib/python3.8/site-packages/dbus/bus.py", line 239, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/app/lib/python3.8/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/app/lib/python3.8/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/app/lib/python3.8/site-packages/dbus/bus.py", line 275, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.8/site-packages/dbus/connection.py", line 650, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```

This happen the first time I run the app, if I use a different console to run the app it opens without the error. The same happen if I click in the app's icon, the first time gnome just wait for the app to open but no window shows up, if I click again in the icon then the window shows up properly. 

I have a GNOME Shell 3.38.4 on a Debian sid. Let me know if you need more info.

**Comment by nekohayo** [comment] 2021-07-11 20:30
Huh, this is odd... I have no idea what this might mean, and I haven't encountered that (apparently others didn't either). Is that still happening consistently for you, or did you just happen to have a broken d-bus on that particular day that got fixed by a reboot?

**Comment by jorgeecardona** [comment] 2021-07-12 13:57
It happens consistently; my current gnome installation runs flawlessly, this is the only thing failing at the moment. I can give you versions of installed packages or content of files on request.

**Comment by Neui** [comment] 2021-07-12 19:10
It seems to be caused by the Hamster plugin. Since it says "ServiceUnknown" I guess you don't have [Hamster](https://github.com/projecthamster/hamster) installed. That it shouldn't block the execution is a bug in my opinion. Try disabling the plugin/extension.

**Comment by nekohayo** [comment] 2022-02-19 05:44
As an additional note: GTG should also probably have a defensive plugin mechanism that doesn't save the activation state of plugins if an error occurs while trying to activate them, but I don't know how hard that would be to accomplish...

**Comment by idle5** [comment] 2022-06-05 21:54
So I downloaded the program from Flathub (6/5/22) and i'm getting a similar issue when trying to enable Hamster time tracking integration after going to options -> plugins. Will try using the .config workaround! 

```
**Context:** Global generic exception
python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: org.freedesktop.DBus.Error.NameHasNoOwner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/plugins.py", line 216, in on_plugin_toggle
    self.pengine.activate_plugins([plugin])
  File "/app/lib/python3.9/site-packages/GTG/core/plugins/engine.py", line 202, in activate_plugins
    plugin.instance.activate(api)
  File "/app/lib/python3.9/site-packages/GTG/plugins/hamster/hamster.py", line 155, in activate
    self.hamster = dbus.SessionBus().get_object('org.gnome.Hamster',
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/app/lib/python3.9/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.2.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.1, PyGObject 3.42.1
* Linux-5.15.0-35-generic-x86_64-with-glibc2.33`

**Comment by AymericDeschard** [comment] 2022-06-29 16:29
Issue raised by @idle5 solved by managing access rights in flatseal https://github.com/getting-things-gnome/gtg/issues/770#issuecomment-1092811829

But, the error message should be more comprehensive and the soft should not crash

**Comment by nekohayo** [comment] 2024-02-26 16:59
Oh, it turns out that a gazillion mysterious report tickets (#962, #963, #983, #990 …) were _all_ duplicates of this issue here!

@flavin would you be willing to try to come up with a fix for this, based on the latest git `master` version in light of the recently merged megaport?

---

Note: this crash is not the same as #961 / #980.

**Closed** 2024-07-17 21:19 UTC
Labels: bug, priority:critical, reproducible-in-git, packaging, plugins
