### ISSUE TITLE
Existing tags of a task do not appear in Modify Tags dialog

### ISSUE THREAD

**Issue by tkdchen** [getting-things-gnome/gtg#444] opened 2020-08-02 08:33 UTC
Steps:

* Launch GTG from master branch
* Select a task
* Right click and click Modify Tags, or just press Ctrl+T
* Only NewTag is present in the text box

Excepted result:

* If a task has no tag, just showing NewTag.
* If a task has tags already, show them in the dialog intead of the NewTag.

**Comment by zeddo123** [comment] 2020-10-28 11:02
Hi, I looked into this and although it's easy to fix for a single task, a problem arises when multiple ones are selected.
The tags that are put in the input field will be added (or removed) to all the tasks. For this reason, we will have to put all tags of all selected tasks in the input field which not be convenient.

I could make it that only when a single task is selected, the tags would be shown. Would that be enough?

**Comment by nekohayo** [comment] 2020-10-28 16:05
Actually a duplicate of #278 (for which I have some reservations, see the comments I wrote there too).

**Closed by nekohayo** 2020-10-28 16:05 UTC
Labels: bug, duplicate, low-hanging-fruit, priority:low, reproducible-in-git
