### ISSUE TITLE
Remove autosave function

### ISSUE THREAD

**Issue by digitalethics** [getting-things-gnome/gtg#427] opened 2020-07-15 12:37 UTC
The autosave function is useful only for note-taking software and document editors, however, in the case of task management software it limits productivity. The reason for this is quite simply, that as a user you lose control over the process of _actively_ creating task lists. Do not underestimate the psychological effect of taking your own tasks seriously when you press <kbd>Enter</kbd>.

**Comment by nekohayo** [comment] 2020-07-17 18:10
Barring any performance issues (which can be solved by fixing issues #270 and #285), I really see no reason at all why GTG shouldn't autosave and propagate changes in semi-realtime, and why autosaving would somehow "limit productivity". The whole point of being productive with a tool is that you don't have to think about the tool, it has to "just work".

On the contrary, the notion/action of manual saving _is_ counterproductive and wasteful to me as a user (I want the computer to figure these things out automatically for me, not make me do "[shit work](https://zachholman.com/posts/shit-work/)™ "). For the same reason why I requested that GNOME automatically purges items older than a certain amount of days in my file manager's recycle bin, or why GTG has an automatic "old deleted tasks" cleanup feature. Editing a task is not a solemn act like signing a treaty with a wax seal!

And furthermore, it's also a matter of data safety:

* On Linux, nothing guarantees that I wouldn't encounter, at any given time, a stupid display server crash or kernel panic—due to some driver bug or OoM—that loses my running GUI apps and/or forces me to hard reset my computer (it happened to me soooo many times)
* In certain parts of the world, electricity is unstable and you can have your desktop computer suddenly turn off on you and lose all unsaved data. You do not want to rely on users remembering to manually save things. Heck, even where I live, where electricity is very stable, I've had the entire city black out for half an hour due to a massive thunderstorm during the night... thankfully, as GTG autosaves my work (and makes backups daily), I didn't lose anything.

And adding yet another button to "Save" adds another level of complexity in the UI, from a design perspective, that I'm not really enthusiastic about.

With all that in mind, and with all due respect, I think I'll consider this request a wontfix. We can always treat the root causes (ex: performance issues for example) rather than throwing out the baby with the bathwater!

**Closed by nekohayo** 2020-07-17 18:10 UTC

**Comment by digitalethics** [comment] 2020-07-17 21:21
Ok, I disagree on all points here but I'll try to get accustomed to the autosave workflow. If the issue persists I'll present my arguments.
