### ISSUE TITLE
Crash caused by double clicking on the "getting started with GTG (read me first)" link

### ISSUE THREAD

**Issue by platypus42** [getting-things-gnome/gtg#701] opened 2021-08-29 02:53 UTC
crash occurs when double clicking on the main link after having read several sublinks. Error message in terminal is simply
 "2021-08-28 22:47:24,633 - WARNING - general_preferences:get_default_editor_font:88 - Using deprecated but still working font way (UnicodeDecodeError('utf-8', b'`\x08\x0b\xb7xU 10', 3, 4, 'invalid start byte'))
Floating point exception (core dumped)" 
Sometimes only the "floating point exception" appears. Restarting the program about 10 times seems to have fixed this

Edit: Issue also occurs when opening task which has subtasks.

**Comment by Neui** [comment] 2021-08-29 10:57
With sublinks you mean subtasks? Did you mark those subtasks as finished? If you did, then it seems you get the same issue as in https://github.com/getting-things-gnome/gtg/issues/699, except it seems you're using the current git version without flatpak, so you probably have to see how you can downgrade(/upgrade?) libpango on your distribution package manager.

**Comment by nekohayo** [comment] 2021-08-31 04:40
The floating point exception is most certainly what was investigated in ticket 699; you are opening the parent task where some of its children tasks are done, therefore in struckthrough format, therefore triggering the Pango bug. Closing as a duplicate of that one unless proven otherwise.

**Closed by nekohayo** 2021-08-31 04:40 UTC
Labels: duplicate, invalid
