### ISSUE TITLE
Add ability to set a custom save location for task file.

### ISSUE THREAD

**Issue by nervecenter** [getting-things-gnome/gtg#588] opened 2021-03-18 01:48 UTC
Allow users to select a custom file location and name for their task file, or open one which already exists. Instead of needing to work with every possible sync service, this can generically work with any directory-based sync service by allowing the user to keep their task file in their Mega or Dropbox or Google Drive sync folder or what-not. Then load it on any machine. Simple.

**Comment by nekohayo** [comment] 2021-03-22 02:00
Hi! I would consider this a duplicate of issue #473 (and thus close it in favor of that one). As you can see in that issue, we don't really see a safe way to accomplish this; you could probably work around the issue on your end using symbolic links.

**Closed by nekohayo** 2021-03-22 02:00 UTC
Labels: duplicate
