### ISSUE TITLE
untouchedTasks Plugin throws ValueError when attempting to check which tasks are "untouched"

### ISSUE THREAD

**Issue by APCBoston** [getting-things-gnome/gtg#926] opened 2022-09-18 12:04 UTC
When checking for untouched tasks, untouchedTasks.py throws an exception at line 114:

` if new_time < today:`

new_time is a `Date` object while `today` is defined at line 103 as a `datetime.datetime` object.  Unfortunately, the comparison operator < is not defined for that pairing.  

I'll have a pull request momentarily to fix this by changing `today` to be a `datetime.date` object.

``` python-traceback
Traceback (most recent call last):
  File "/home/andy/development/gtg/.local_build/install/lib/python3/dist-packages/GTG/plugins/untouched_tasks/untouchedTasks.py", line 150, in on_preferences_ok
    self.preferences_apply()
  File "/home/andy/development/gtg/.local_build/install/lib/python3/dist-packages/GTG/plugins/untouched_tasks/untouchedTasks.py", line 170, in preferences_apply
    self.add_untouched_tag()
  File "/home/andy/development/gtg/.local_build/install/lib/python3/dist-packages/GTG/plugins/untouched_tasks/untouchedTasks.py", line 114, in add_untouched_tag
    if new_time < today:
TypeError: can't compare datetime.datetime to datetime.date


**Software versions:**
* GTG (debug version) v0.6-68-gf4d2fc81
* CPython 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
* GTK 3.24.33, GLib 2.71.3
* PyGLib 3.42.1, PyGObject 3.42.1
* Linux-5.15.0-46-generic-x86_64-with-glibc2.35 ```

**Comment by Neui** [comment] 2022-09-18 12:13
Duplicate of #912

**Comment by APCBoston** [comment] 2022-09-18 12:23
> Duplicate of #912 I believe.

I think you're right.  I'll cross-reference 912 in my pull request.

**Closed** 2022-10-15 23:36 UTC
