### ISSUE TITLE
Issues when trying to add a synchronization service

### ISSUE THREAD

**Issue by ceskopenta** [getting-things-gnome/gtg#947] opened 2023-01-01 11:42 UTC
I copied and pasted the reports generated by the software.
I have Fedora 37, I had the same problem with Fedora 36.
If I use SNAP Store to install Getting Things Gnome, and I try to add a synchronization service, I have this report.

---------------------------------------------------------

**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/snap/getting-things-gnome/7/usr/lib/python3/dist-packages/GTG/gtk/backends/__init__.py", line 231, in on_add_button
    self.add_panel.refresh_backends()
  File "/snap/getting-things-gnome/7/usr/lib/python3/dist-packages/GTG/gtk/backends/addpanel.py", line 141, in refresh_backends
    self.combo_types.refresh()
  File "/snap/getting-things-gnome/7/usr/lib/python3/dist-packages/GTG/gtk/backends/backendscombo.py", line 81, in refresh
    pixbuf = self.dialog.get_pixbuf_from_icon_name(module.Backend.get_icon(), 16)
  File "/snap/getting-things-gnome/7/usr/lib/python3/dist-packages/GTG/gtk/backends/__init__.py", line 121, in get_pixbuf_from_icon_name
    return Gtk.IconTheme.get_default().load_icon(name, height, 0)
gi.repository.GLib.GError: gtk-icon-theme-error-quark: Icona «applications-internet» non presente nel tema Adwaita (0)
```

**Software versions:**
* Getting Things GNOME! v0.6-20-g55a1a624-dirty
* CPython 3.8.10 (default, Nov 14 2022, 12:59:47)   [GCC 9.4.0]
* GTK 3.24.34, GLib 2.64.6
* PyGLib 3.36.2, PyGObject 3.36.2
* Linux-6.0.15-300.fc37.x86_64-x86_64-with-glibc2.29

---------------------------------------------------------

Insted, if I try to use the default Software app of Fedora to install Getting Things Gnome, I have this report as soon as I try to open Getting Things Gnome.

**Context:** Activation

```python-traceback
None```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.2, PyGObject 3.42.2
* Linux-6.0.15-300.fc37.x86_64-x86_64-with-glibc2.33

**Comment by Neui** [comment] 2023-01-01 20:19
Duplicate of #846

**Closed** 2023-01-06 14:28 UTC
