### ISSUE TITLE
Font resizing while typing

### ISSUE THREAD

**Issue by primal-buddhist** [getting-things-gnome/gtg#633] opened 2021-04-13 15:48 UTC
(Fairly sure this one will have been logged but just can't find it!)

At some point in the last week, I assume 0.5, when I type into the task name area,  I see characters in a small font that immediately resize to the large font. Pretty distracting and unusual :-)

**Comment by nekohayo** [comment] 2021-04-13 17:34
Yup, duplicate of #617 essentially!

**Closed by nekohayo** 2021-04-13 17:34 UTC
Labels: duplicate, question
