### ISSUE TITLE
BUG: Tagging in a NEW mastertask with subtasks creates mangled text in the children

### ISSUE THREAD

**Issue by primal-buddhist** [getting-things-gnome/gtg#417] opened 2020-07-13 14:04 UTC
Adding a tag after creating subtasks for the first time in a new master task creates garbled text that resembles the tag in the child tasks. 

Version .4, rebased last night. 

Steps to reproduce

1. Add new task
2. Create new task text using - subtask1 [enter] to create multiple subtasks
4. Watch the subtasks appear in real time in the main window.All good up to this point.
5. Type @tagtagtag
6. Watch the garbled versions of tagtagtag appear in real time against all tasks
6. Take screenshot

First screenshot shows the bug as it is happening - I am typing tagtagtag and the garbled letters are appearing in real time. It seems like it sends the tag text in chunks as if they were new tags, but also not as @tags 

The second screenshot shows the result in the subtask window. 

![gtgtagbugscreen](https://user-images.githubusercontent.com/26062201/87312128-132fad00-c518-11ea-9799-15c8a17d14c5.png)
![gtgtagbug2](https://user-images.githubusercontent.com/26062201/87312854-065f8900-c519-11ea-90ec-85242f4df2ac.png)

**Comment by primal-buddhist** [comment] 2020-07-13 15:00
so testing, typing 12345 gets 12, 123, 1234, 12345

If you backspace and retype it adds it again

**Comment by diegogangl** [comment] 2020-07-14 23:25
This is techinically a duplicate of #45 . This is fixed in the new taskview widget, but it's not in master yet.
Thanks for reporting!

**Closed by diegogangl** 2020-07-14 23:25 UTC
