### ISSUE TITLE
Build fails on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by vjcalel** [getting-things-gnome/gtg#242] opened 2020-02-12 06:49 UTC
`pip3 install -r requirements.txt`

returns

```
Downloading https://files.pythonhosted.org/packages/25/95/ac361f06789c7dad19c37f4d7043df9275f416dffcdc44e22c3befeb7b08/pycairo-1.19.0.tar.gz (200kB)
    100% |████████████████████████████████| 204kB 109kB/s 
Building wheels for collected packages: PyGObject, pycairo
  Running setup.py bdist_wheel for PyGObject ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7m2qvrt6/PyGObject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpkkt7aefppip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for PyGObject
  Running setup.py clean for PyGObject
  Running setup.py bdist_wheel for pycairo ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7m2qvrt6/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpn78bf02xpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pycairo
  Running setup.py clean for pycairo
Failed to build PyGObject pycairo
Installing collected packages: six, nose, spec, liblarch, pycairo, PyGObject
  Found existing installation: liblarch 3.0.0
    Uninstalling liblarch-3.0.0:
      Successfully uninstalled liblarch-3.0.0
  Running setup.py develop for liblarch
  Running setup.py install for pycairo ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7m2qvrt6/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-fda5_0n0-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/cairo
    copying cairo/__init__.py -> build/lib.linux-x86_64-3.6/cairo
    copying cairo/__init__.pyi -> build/lib.linux-x86_64-3.6/cairo
    copying cairo/py.typed -> build/lib.linux-x86_64-3.6/cairo
    running build_ext
    Package cairo was not found in the pkg-config search path.
    Perhaps you should add the directory containing `cairo.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'cairo' found
    Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1.
```
And after that running ./gtg.sh returns error:

```
  from gi.repository import GObject, Gtk, Gdk
Traceback (most recent call last):
  File "./GTG/gtg", line 251, in <module>
    main()
  File "./GTG/gtg", line 197, in main
    manager = Manager(req)
  File "/home/pcuser/gtg-master/gtg/GTG/gtk/manager.py", line 75, in __init__
    self.browser = TaskBrowser(self.req, self)
  File "/home/pcuser/gtg-master/gtg/GTG/gtk/browser/browser.py", line 98, in __init__
    self.builder.add_from_file(GnomeConfig.BROWSER_UI_FILE)
GLib.Error: gtk-builder-error-quark: /home/pcuser/gtg-master/gtg/GTG/gtk/browser/taskbrowser.ui:507:67 Invalid property: GtkEntry.enable_emoji_completion (11)
```

**Comment by tkdchen** [comment] 2020-02-12 11:15
You need to install cairo dev package from Ubuntu package repositories. I'm not using Ubuntu, after searching from the Internet, I think `libcairo2-dev` should be the one you need to install.

**Comment by diegogangl** [comment] 2020-02-13 15:09
```GLib.Error: gtk-builder-error-quark: /home/pcuser/gtg-master/gtg/GTG/gtk/browser/taskbrowser.ui:507:67 Invalid property: GtkEntry.enable_emoji_completion (11)```

Besides Cairo, this looks like an error caused by using an older GTK version that doesn't have `GtkEntry.enable_emoji_completion`. Could you[ follow this](https://askubuntu.com/questions/78377/is-there-a-way-to-know-which-gtk-version-is-installed-using-the-command-line) and tell us which GTK version you are running?

**Comment by vjcalel** [comment] 2020-02-18 07:39
Thanks.

I have 3.22 (gtk-3)

```
libgtk-3-0:
  Installed: (none)
  Candidate: 3.22.30-1ubuntu4
```

Installing libcairo2-dev didn't help. It's the library for c, c++, not sure what sort of binding it provides for python. On Ubuntu, usually they are provided by gir1.2-<package-name> .

Also liblarch is also python2 (that's what I am getting) ? Will it work with python3 codebase ?

**Comment by diegogangl** [comment] 2020-02-18 23:45
Liblarch in master is Python3. Here's how to install it:
```pip3 install --user -e git+git://github.com/getting-things-gnome/liblarch.git#egg=liblarch```

As for emoji completion. Indeed it seems it was added in 3.24. Could you try the `no_emoji_autocomplete` branch and see if it works? It's kinda weird Glade didn't say anything about this, we're supposedly targeting GTK 3.20

**Comment by clobrano** [comment] 2020-02-20 13:11
I have the same problem and moving to branch `no_emoji_autocomplete` fixes the problem with emoji, but it stops soon after with this

```
./GTG/gtg:53: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository.Gdk import Screen
/home/TMT/carlolo/toolkit/custom/gtg/GTG/tools/keyring.py:20: PyGIWarning: GnomeKeyring was imported without specifying a version first. Use gi.require_version('GnomeKeyring', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GnomeKeyring
/home/TMT/carlolo/toolkit/custom/gtg/GTG/gtk/manager.py:21: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Gtk, Gdk
Traceback (most recent call last):
  File "./GTG/gtg", line 249, in <module>
    main()
  File "./GTG/gtg", line 196, in main
    manager = Manager(req)
  File "/home/TMT/carlolo/toolkit/custom/gtg/GTG/gtk/manager.py", line 84, in __init__
    self.preferences = Preferences(self.req, self)
  File "/home/TMT/carlolo/toolkit/custom/gtg/GTG/gtk/preferences.py", line 48, in __init__
    self.add_page(GeneralPreferences(req, vmanager))
  File "/home/TMT/carlolo/toolkit/custom/gtg/GTG/gtk/general_preferences.py", line 40, in __init__
    builder.add_from_file(self.GENERAL_PREFERENCES_UI)
GLib.Error: gtk-builder-error-quark: /home/TMT/carlolo/toolkit/custom/gtg/GTG/gtk/ui/general_preferences.ui:296:56 Invalid property: GtkFontButton.language (11)
```

**Comment by nekohayo** [comment] 2020-02-20 16:31
Just tagging this issue properly to reflect the fact that it "must" work on Ubuntu (and that we will need to be sure our build documentation is up to date for it) because it's still the most popular distro, which of course means the most popular vector for testers and potential contributors.

I haven't tested it myself but hope to, when I can find some time and the power supply of a spare computer for this; probably others will beat me to it when it comes to figuring out how to fix and document this however :)

**Comment by clobrano** [comment] 2020-02-20 16:33
An important detail: it works fine on Ubuntu 19.10
Still 18.04 is an LTS and it's important, but I had no problem in 19.10 after installing the requirements

**Comment by nekohayo** [comment] 2020-02-20 16:59
Oh! Retitling for clarity then...

Unless there's a way to fix this without going insane, it might be more productive to set the requirements to be "19.10 and newer" considering that the next Ubuntu LTS is coming out in merely two months (on April 23rd)...

**Comment by diegogangl** [comment] 2020-02-20 16:59
Hey, @clobrano I pushed again to no emojis branch removing the language property. Could you give it another try?

> Still 18.04 is an LTS and it's important, but I had no problem in 19.10 after installing the requirements

Yep, 19.10 has the latest Gtk so no problems. Maybe we should try to move to flatpaks for development sooner, that would take care of all dependency issues.

**Comment by clobrano** [comment] 2020-02-21 08:25
> Hey, @clobrano I pushed again to the no emojis branch removing the language property. Could you give it another try?
> 
> > Still 18.04 is an LTS and it's important, but I had no problem in 19.10 after installing the requirements
> 
> Yep, 19.10 has the latest Gtk so no problems. Maybe we should try to move to flatpaks for development sooner, that would take care of all dependency issues.

cool, this branch is working now!

**Comment by vjcalel** [comment] 2020-02-21 12:34
Thanks. It now works.

**Comment by diegogangl** [comment] 2020-02-21 17:48
Alright folks, thanks for reporting! I pushed the changes to master so you can pull from there now.

**Closed** 2020-02-21 17:48 UTC
Labels: documentation, priority:high, question, reproducible-in-git

**Comment by XioNoX** [comment] 2020-04-27 08:33
For the record, on Ubuntu 20.04:
* I had the error `No package 'cairo' found` during `pip3 install -r requirements.txt`, installing `libcairo2-dev` solved it.
* I then had `No package 'gobject-introspection-1.0' found` but the error output rightfully suggested to run `sudo apt install libgirepository1.0-dev`
* Last one was `No package 'dbus-1' found` solved by installing `libdbus-glib-1-dev`

**Comment by nekohayo** [comment] 2020-04-28 17:29
Thanks for the feedback! Weird how I didn't encounter those missing dependencies myself when testing with Ubuntu 20.04. Or maybe I did and forgot.

For cairo, it seems "pycairo" might be the thing to list in the requirements.txt? It's weird that https://pypi.org/project/pycairo/ mentions cairo 1.13.x while your Ubuntu/deb/apt package mentions "libcairo2". Looking at the cairo-related packages in Fedora, I see that "cairo" is version 1.16.0 and "python3-cairo" is version 1.18.1, so it seems no "cairo 2" exists and Debian/Ubuntu's package naming is just weird. I also wondered if cairo was handled through gobject introspection nowadays, but the existence of python3-cairo and python3-cairo-devel packages in Fedora makes me think that nope, it's just old-school bindings. So... should we just put "pycairo" in requirements.txt and mention the distro packages for it in README.md?

As for the other two, gobject introspection and dbus-glib-1... I don't know / am not sure what to list there. Seems like it would be https://pypi.org/project/PyGObject/ (which is already listed in requirements.txt, so isn't it that pip actually worked as intended on your end by suggesting the APT command?) and https://pypi.org/project/dbus-python/ (not sure at all this is the right one)?

**Comment by nekohayo** [comment] 2020-04-28 17:42
Turns out that python3-dbus and python3-cairo also exist as packages on Ubuntu, and seem to be sufficient (no need for those -dev packages) from what I could see on my test machine. Interestingly, it seems the cairo dependency gets pulled by the PyGObject ("gobject-introspection") dependency already. The "gobject-introspection" package also exists on Ubuntu 20.04, in addition to the libgirepository1 package and such (and no need to have the -dev variants installed). So now I'm utterly confused...
