### ISSUE TITLE
allow assigning tags by drag and dropping tasks on them in the sidebar

### ISSUE THREAD

**Issue by FlorianLudwig** [getting-things-gnome/gtg#420] opened 2020-07-14 06:40 UTC
Draging one or multiple tasks onto a tag in the sidebar should assign that tag to the task(s).

**Comment by nekohayo** [comment] 2020-07-14 15:29
It already workes for the single task usecase, just not for the multiple drag case (issue #406), so closing as a duplicate of that.

**Closed by nekohayo** 2020-07-14 15:29 UTC
Labels: duplicate
