### ISSUE TITLE
Flatpak: cant enable synchronization

### ISSUE THREAD

**Issue by LeSnake04** [getting-things-gnome/gtg#879] opened 2022-04-03 15:42 UTC
I can't enable synchronization, I get this error and there is no option to select on select synchronization service. 

**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/backends/__init__.py", line 231, in on_add_button
    self.add_panel.refresh_backends()
  File "/app/lib/python3.9/site-packages/GTG/gtk/backends/addpanel.py", line 141, in refresh_backends
    self.combo_types.refresh()
  File "/app/lib/python3.9/site-packages/GTG/gtk/backends/backendscombo.py", line 81, in refresh
    pixbuf = self.dialog.get_pixbuf_from_icon_name(module.Backend.get_icon(), 16)
  File "/app/lib/python3.9/site-packages/GTG/gtk/backends/__init__.py", line 121, in get_pixbuf_from_icon_name
    return Gtk.IconTheme.get_default().load_icon(name, height, 0)
gi.repository.GLib.GError: g-io-error-quark: Failed to load /run/host/user-share/icons/Breeze-Noir-White-Blue/apps/16/applications-internet.svg: Fehler beim Öffnen der Datei »/run/host/user-share/icons/Breeze-Noir-White-Blue/apps/16/applications-internet.svg«: No such file or directory (1)
```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.2.0]
* GTK 3.24.33, GLib 2.70.5
* PyGLib 3.42.0, PyGObject 3.42.0
* Linux-5.16.14-1-MANJARO-x86_64-with-glibc2.33

**Comment by LeSnake04** [comment] 2022-04-03 15:44
likely related: #846

**Comment by nekohayo** [comment] 2022-07-10 15:20
Yup, I think you guessed right and that this is a duplicate of 846; closing this as such.

**Closed by nekohayo** 2022-07-10 15:20 UTC
Labels: duplicate, plugins
