### ISSUE TITLE
Subtasks listed alphabetically instead of the order in which they were added

### ISSUE THREAD

**Issue by cajhne** [getting-things-gnome/gtg#451] opened 2020-09-01 12:10 UTC
I don't know of anyone who completes tasks in alphabetical order, thus I recommend that the order in which they are listed be preserved in the list by default. I know that this can be remedied by adding numbers or start and end dates for everything, however that's sometimes an excessive amount of work for a to-do list which may change and require re-numbering, and start and end dates/times are not always known.

Steps to reproduce:
1. Add task
2. Add sub-tasks with - character preceeding
3. exit out of the task editor:

Result: Tasks re-arranged in alphabetical order
What should have happened: Task order should be maintained as originally written by the user.

**Comment by nekohayo** [comment] 2020-09-01 14:56
Hi! Closing as duplicate of issue #70

**Closed by nekohayo** 2020-09-01 14:56 UTC
