### ISSUE TITLE
GTG does not start correctly

### ISSUE THREAD

**Issue by EmmanuelP** [getting-things-gnome/gtg#693] opened 2021-07-28 16:08 UTC
Launching flatpak GTG, the GUI does not show. Using `flatpak run`, I get the following debug output:

```
flatpak run org.gnome.GTG
GNOME keyring not found, passwords will be not stored after restarting GTG
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 97, in do_startup
    datastore.register_backend(backend_dic)
  File "/app/lib/python3.8/site-packages/GTG/core/datastore.py", line 459, in register_backend
    source.initialize(connect_signals=False)
  File "/app/lib/python3.8/site-packages/GTG/core/datastore.py", line 822, in initialize
    self.backend.initialize()
  File "/app/lib/python3.8/site-packages/GTG/backends/backend_localfile.py", line 134, in initialize
    self.datastore.load_tag_tree(self.tag_tree)
  File "/app/lib/python3.8/site-packages/GTG/core/datastore.py", line 251, in load_tag_tree
    tag = self.new_tag(name, tag_attrs, tid)
  File "/app/lib/python3.8/site-packages/GTG/core/datastore.py", line 122, in new_tag
    self._add_new_tag(name, tag, self.treefactory.tag_filter, parameters)
  File "/app/lib/python3.8/site-packages/GTG/core/datastore.py", line 108, in _add_new_tag
    raise IndexError(f'tag {name} was already in the datastore')
IndexError: tag Adv was already in the datastore
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 123, in do_activate
    self.init_shared()
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 160, in init_shared
    self.init_browser()
  File "/app/lib/python3.8/site-packages/GTG/gtk/application.py", line 168, in init_browser
    self.browser = MainWindow(self.req, self)
  File "/app/lib/python3.8/site-packages/GTG/gtk/browser/main_window.py", line 70, in __init__
    self.config = self.req.get_config('browser')
AttributeError: 'NoneType' object has no attribute 'get_config'
```

The last time I have used GTG, I have modifed a tag named `Adv+` to `Adv`, while there was already an `Adv` tag, which could explain: `IndexError: tag Adv was already in the datastore`.

**Comment by EmmanuelP** [comment] 2021-07-28 16:31
I have fixed my issue by editing gtg-data.xml, and renamed `Adv` tag back to `Adv+`.

I coudld have used a backup, but I would have lost my last editions.

It looks like a tag with a '+' in its name causes serious issue in GTG. Each time I opened a task, another instance of @Adv+ was added in the task body.

**Comment by diegogangl** [comment] 2021-11-15 17:42
This was caused by the taskview not recognizing `+` and a few other symbols as valid in tags. It has been fixed in master and will be in 0.6

**Closed by diegogangl** 2021-11-15 17:42 UTC
Labels: bug

**Comment by Neui** [comment] 2021-11-15 17:49
I am not sure if this is fixed, but I also haven't looked at it in depth yet.
From the following, it seems taskview not recognizing `+` is not the "problem", but rather "renaming" itself:

> The last time I have used GTG, I have modifed a tag named `Adv+` to `Adv`, while there was already an `Adv` tag, which could explain: `IndexError: tag Adv was already in the datastore`.

**Comment by diegogangl** [comment] 2021-11-15 17:53
Ah just noticed that it fails _after_ restarting, I thought it was that bug. I'll take a deeper look in the evening

**Comment by diegogangl** [comment] 2021-11-17 17:22
Pushed an actual fix for this
