### ISSUE TITLE
Fatal internal error problem 

### ISSUE THREAD

**Issue by karthy257** [getting-things-gnome/gtg#983] opened 2023-07-26 19:45 UTC
**Context:** Activation

```python-traceback
None```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.2, PyGObject 3.42.2
* Linux-5.19.0-50-generic-x86_64-with-glibc2.33

**Comment by nekohayo** [comment] 2024-02-26 16:45
Invalid/unactionable description/report.

Probably a duplicate of #962

**Closed by nekohayo** 2024-02-26 16:45 UTC
Labels: duplicate, invalid
