### ISSUE TITLE
GTG crashes at startup

### ISSUE THREAD

**Issue by drtsdgdj** [getting-things-gnome/gtg#968] opened 2023-04-14 11:41 UTC
**Context:** Startup

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 110, in do_startup
    for backend_dic in BackendFactory().get_saved_backends_list():
  File "/app/lib/python3.9/site-packages/GTG/backends/__init__.py", line 143, in get_saved_backends_list
    module = self.get_backend(settings.get('module'))
  File "/app/lib/python3.9/site-packages/GTG/core/config.py", line 164, in get
    raise ValueError(
ValueError: No valid configuration value or default value was found for %s in %s
```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.34, GLib 2.70.5
* PyGLib 3.42.2, PyGObject 3.42.2

**Comment by nekohayo** [comment] 2024-02-26 17:10
Duplicate of #845

**Closed by nekohayo** 2024-02-26 17:10 UTC
Labels: duplicate, plugins
