### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by daniel-sanchez-marzoa** [getting-things-gnome/gtg#880] opened 2022-04-05 18:28 UTC
I have activated dark mode, but it remains in light mode even after restarting the application. The setting is saved properly though. My system is:

![imagen](https://user-images.githubusercontent.com/78441017/161824758-a7501ad7-7ef9-4de1-bd32-647a30f02ef2.png)

**Comment by kocio-pl** [comment] 2022-04-07 11:22
It's a duplicate of #878.

**Closed** 2022-04-22 22:19 UTC
