### ISSUE TITLE
Hamster integration

### ISSUE THREAD

**Issue by pwr33** [getting-things-gnome/gtg#252] opened 2020-03-06 09:22 UTC
Got github version of hamster installed and the integration of old packaged gtg to new Hamster mostly works, but this latest gtg not got hamster plugin working.  I think it is a great feature to start/stop hamster time recording from gtg

My suggestion would be to simplify the interface to hamster,

. Only have the functionality to start and stop a gtg task in hamster
...also only pass the gtg task title to hamster, the gtg detail makes hamster report look unreadable
...make hamster category the first tag you find in the gtg item detail
. Do not bother with back-collecting the hamster data into gtg, 
...i.e. in GTG do not bother to display the time recorded on a task, already got that in hamster

Similar with Gnote integration, only allow one option to manually pass an item from gtg to gnote.  I would have the default option to rename the note (maybe prefix with gtg: or something) when passing data to gnote to avoid the merge/latest data complications.  If the note exists when passing to gnote then prompt what to do, or use config dialog to set what to do.  But having a gtg: prefix on the note would overcome the overwriting the original gtg note problem.  (not yet been able to compile the github copy of gnote, compile errors)

The auto sync. feature in my opinion is dangerous, as may not want to delete an item in one app when deleted in the other etc..  and the syncing plugin stops every now and then anyway

Keep it simple eh!  let different apps do what they were designed to do on their own local copy of data, do not encroach on their functional territory.... but allow driving them.

I reckon people from all 3 projects should confer, as they are all good complementary applications, gnotes needs some work to have multi-tag/category linking as a knowledge database as ultimate end-point store of information and gtg and xhamster as immediate operators on data...

**Comment by pwr33** [comment] 2020-03-11 00:05
On reflection the problem with using any or all of these three vs. just the quite well refined notepad-app flat file method is always, where did I make that note... (can use your own tags in flat file, though featherpad is a p.i.t.a. pasting contents of file rather than a copied thunar file reference)

so all is useful is top level line of task unless can collate all 3 together in where to singularly take notes and do all tagging in one scope

so hamster is prime, though gtg is quite good esp. with hamster link, and gnotes is quite weak, no multi-tagging.

**Comment by nekohayo** [comment] 2020-05-12 16:25
Hi @pwr33, I'm not sure why I missed you filing this ticket earlier, but in any case I suppose it should be considered a duplicate of #114 unless there there are specific things to have as separate tickets. You could contribute general knowledge/implementation suggestions in #114.

Are you offering to work on it? We need someone to work on it or it won't happen.

**Closed by nekohayo** 2020-05-12 16:25 UTC
Labels: duplicate, plugins
