### ISSUE TITLE
UI enhancement - show the name of parent after the sub task text in the main list

### ISSUE THREAD

**Issue by primal-buddhist** [getting-things-gnome/gtg#611] opened 2021-04-03 20:40 UTC
Hi

So often I put in a task and then start brainstorming the sub tasks inside the notes area. I often put in quite short titles that are only useful _in context_.

Eg, I start a task "Get the guitar working on the laptop"

I then make a list of things that that would need, sometimes questions.

eg "Will need more storage"

So then that appears on the actionable list. It is a little out of context. 

What I think would be nice is if the sub task had some reference to the parent after it. The current UI has a lot of space available.

Something like:

**Will need more storage** _(Get the guitar working on the laptop)_

Might help with natural prioritising?

**Comment by diegogangl** [comment] 2021-04-05 21:16
Hey, we talked about this somewhat recently in the chat. It's one of the reasons why I don't use the actionable tab much. 
There were some issues with showing parents though. This is one of the things we could fix with a more modern list UI
Also see #14

**Comment by nekohayo** [comment] 2021-07-11 21:28
Yeah I'm not sure how to solve this one here because it kinda conflicts with the feature where the descriptive text gets previewed in gray after the task title in the task browser's listview rows; and I've pretty much never run into a situation where the task title + description combined are short enough to not exceed the line's length, so the parent task name would not be shown anyway.

Other than implementing issue #14, the way I imagined could solve your problem was by using tooltips (issue #240). Would that work for you @primal-buddhist? If so, we could close this ticket here as a duplicate of #240.

**Comment by primal-buddhist** [comment] 2021-07-12 16:24
Yes by all means close this one :-)

**Closed** 2021-07-12 16:37 UTC
Labels: duplicate, enhancement
