### ISSUE TITLE
Dark theme not working in Cinnamon

### ISSUE THREAD

**Issue by tetrahedon7** [getting-things-gnome/gtg#649] opened 2021-04-28 07:19 UTC
OS: Linux Mint 20.1 Cinnamon (4.8.6)
Version: 0.5

The universal dark theme is not making the GTG window dark. Switching on "Dark mode" from Preferences also does nothing. Only for certain dark Cinnamon dark themes (Arc-Dark and Adwaita-Dark) is the window dark themed.

**Comment by diegogangl** [comment] 2021-04-29 22:05
Hi, what do you mean by "universal dark theme"? Is that a switch in Cinnamon? Note that we only offically support Adwaita.

**Comment by idoric** [comment] 2021-07-01 20:50
I don't know if this is the same bug or if it deserves to open another issue, but with a Fedora 34 (fresh install) and GTG 0.5 flatpaked, I have the same kind of problem, except here the dark theme is not applied if this is Adwaita-dark, but is applied when this is HighContrastInverse. (And switching on "Dark mode" from Preferences also does nothing.)

**Comment by idoric** [comment] 2021-07-10 19:14
I don't know which update of which subsystem fixed the problem, but now everything is working fine so the problem was not with GTG.

**Comment by nekohayo** [comment] 2021-07-11 17:42
I am guessing that this would be because Flatpak isolates your system themes from the sandboxed applications, see this explanation for example: https://www.linuxuprising.com/2018/05/how-to-get-flatpak-apps-to-use-correct.html

Presuming that's the cause, and considering that GTG is mostly (almost exclusively) tested with Adwaita, I'll close this as something that we can't really fix ourselves.

**Closed by nekohayo** 2021-07-11 17:42 UTC
Labels: needinfo
