### ISSUE TITLE
Parent tasks can corrupt themselves when a subtask's title starts with a tag, preventing opening the parent task (traceback where n.firstChild is None, so has no attribute 'nodeValue')

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#45] opened 2014-08-17 18:36 UTC
Initially filed at https://bugs.launchpad.net/gtg/+bug/1356130

I've been using 0.3.1 without problems for nearly a year, and now I'me starting to encounter some problems. I'm not using any synchronization plugins.

It seems the cause is that some tasks become like this eventually:

```
 <task id="4719fc1a-d78b-427f-abe4-394227009cb7" status="Active" tags="@contrats,@phone" uuid="baaadd00-fdb6-4b5d-b3bd-8b1d258a24b2">
  <title>faire une offre fixed cost + contrat, à test@example.com ; JFDI</title>
  <duedate>2014-08-14</duedate>
  <modified>2014-08-12T15:00:54</modified>
  <subtask>70b62c0f-e3d6-485a-827e-d99a461f2945</subtask>
  <content>&lt;tag&gt;@contrats&lt;/tag&gt;,
 &lt;tag/&gt; John Smith to collect his address &amp;quot;for his own good&amp;quot;</content>
  <task-remote-ids/>
 </task>
```

The problem is that after restarting gtg, I try to open up the task, and I can't because I hit this traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/GTG/gtk/editor/taskviewserial.py", line 158, in unserialize
    success = self.parsexml(content_buf, ite, element.firstChild)
  File "/usr/lib/python2.7/site-packages/GTG/gtk/editor/taskviewserial.py", line 207, in parsexml
    text = n.firstChild.nodeValue
AttributeError: 'NoneType' object has no attribute 'nodeValue'
```

Now, looking at the offending code, I see this:

```
                    if n.nodeName == "subtask":
                        tid = n.firstChild.nodeValue
                        # We remove the added subtask from the list
                        # Of known subtasks
                        # If the subtask is not in the list, we don't write it
                        if tid in subtasks:
                            subtasks.remove(tid)
                            line_nbr = itera.get_line()
                            self.tv.write_subtask(buf, line_nbr, tid)
                    elif n.nodeName == "tag":
                        text = n.firstChild.nodeValue
                        if text:
                            self.insert_tag(buf, text, itera)
                            # We remove the added tag from the tag list
                            # of known tag for this task
                            taglist2.append(text)
```

Shouldn't it be something like this instead (just guessing)? :

```
                    if n.nodeName == "subtask" and hasattr(n, "firstChild"):
                        tid = n.firstChild.nodeValue
                        # We remove the added subtask from the list
                        # Of known subtasks
                        # If the subtask is not in the list, we don't write it
                        if tid in subtasks:
                            subtasks.remove(tid)
                            line_nbr = itera.get_line()
                            self.tv.write_subtask(buf, line_nbr, tid)
                    elif n.nodeName == "tag" and hasattr(n, "firstChild"):
                        text = n.firstChild.nodeValue
                        if text:
                            self.insert_tag(buf, text, itera)
                            # We remove the added tag from the tag list
                            # of known tag for this task
                            taglist2.append(text)
```

**Comment by nekohayo** [comment] 2020-02-25 18:34
I hit the same exact traceback again today with the 0.3.1 version (haven't tested if the git version is still affected, but presumably with the instructions above it should be possible to test it) and wanted to add another way I triggered this:

1. I created a task titled "lorsque tous les comptes payés, email les états à Mich" tagged `@finance`
2. In there, I created a subtask "Request tous mes états de comptes"
3. **While keeping the parent task open,** I opened the subtask, changed its `@finance` tag to `@accounting`, and edited the title to prefix it with `@phone Bob to`, so "`@phone` Bob to request tous mes états de comptes
4. Closed the child task, notice the parent task's subtask line didn't get immediately updated
5. Close the parent task, reopen it (sometimes it might need restarting the application, but it will keep happening)

**Comment by diegogangl** [comment] 2020-03-22 00:30
This happens in master too. Did some digging and it seems like it's getting confused the second time you open it. It parses the tag in the subtask as a tag of the main task and writes some incorrect xml.

```xml
	<task id="4d722e50-bea7-419e-8f7a-53b3687465c7" status="Active" tags="@something,@phone" uuid="e77a4c38-f7bc-4524-8bbc-4820c4c80b42">
		<title>Test</title>
		<addeddate>2020-03-21T21:29:30</addeddate>
		<modified>2020-03-21T21:30:01</modified>
		<subtask>d90eab25-a0a5-4309-aa4b-9c1f13a3b212</subtask>
		<content>&lt;tag&gt;@something&lt;/tag&gt;

 &lt;tag/&gt; subtest

</content>
		<task-remote-ids/>
	</task>
```

**Comment by diegogangl** [comment] 2020-03-22 22:52
I can confirm this bug happens when adding a tag in a subtask. From the point of view of the parser, it's a gtkTextTag inside a gtkTextTag.  @ploum It doesn't look like this is supported at all in the serializer?

**Comment by ploum** [comment] 2020-03-23 12:39
It should work (and it has worked) but it's a bug that comes back from time to time. The serializer is very fragile because it serializes to XML and sometimes serializes twice so it becomes XML serialized in XML.

To be honest, I think that one big big work at some point would be to replace XML backend by sqlite. We choose XML so we could manually tweak our files and save them easily when we started developing. In the long term, it was a bad idea.

**Comment by diegogangl** [comment] 2020-03-25 22:14
Funny some time ago I was looking at the filtering and search code thinking "this looks like SQL queries in python" :)

We should evaluate that change in the future for sure. Maybe we could improve performance doing all the filtering and sorting in SQL.

**Comment by nekohayo** [comment] 2020-04-16 22:39
As a straightforward solution has not been found for this yet, and since the issue is not a regression (it was already present in 0.3.x at least), deferring this to the 0.5 release milestone (tentatively)...

**Comment by nekohayo** [comment] 2020-06-05 04:50
I ran into this again today with the git version. As an additional data point, here's the similar-looking traceback:

```
  File "GTG/gtk/browser/main_window.py", line 940, in on_edit_active_task
    self.app.open_task(tid)
  File "GTG/gtk/application.py", line 413, in open_task
    editor = TaskEditor(requester=self.req, app=self, task=task,
  File "GTG/gtk/editor/editor.py", line 190, in __init__
    self.textview.insert(f"{texte}")
  File "GTG/gtk/editor/taskview.py", line 279, in insert
    self.unserializer.unserialize(
  File "GTG/gtk/editor/serialize.py", line 173, in unserialize
    success = self.parsexml(content_buf, ite, element.firstChild)
  File "GTG/gtk/editor/serialize.py", line 222, in parsexml
    text = n.firstChild.nodeValue
AttributeError: 'NoneType' object has no attribute 'nodeValue'
```

...and here's how I did it: I had a task titled "Visit Iceland", with two levels of parents above, and 6 subtasks (some two-levels deep). At some point, while the rest of the task windows were closed, I edited one subtask to have it start with a tag in the title, "`@phone Björk`". Later, when I went back to the "Visit Iceland" task and hit Enter below the title to add a description to the task, "Forget about Norway!", the corruption then occurred when I closed/saved that task. Afterwards, GTG refuses to open the task editor for that task, producing the traceback above.

Inspecting the xml flie and comparing it to the previous backup, I see the same suspicious `&lt;tag/&gt;` present at the beginning of the line of the incriminating subtask, instead of  `&lt;subtask&gt;the_task_id`, as we can see in this visual diff (broken version on the left, previous working version on the right):

![Screenshot from 2020-06-05 00-21-33 borked XML - crop](https://user-images.githubusercontent.com/479401/83837011-35394280-a6c3-11ea-9121-44ee6ca017e5.png)

If I manually repair, as a workaround, the contents of the content tag for the task that refuses to open, like so:

```
		<content>&lt;tag&gt;@travels&lt;/tag&gt;

Forget about Norway!
→   &lt;subtask&gt;47@1&lt;/subtask&gt;
→   &lt;subtask&gt;48@1&lt;/subtask&gt;
→   &lt;subtask&gt;50@1&lt;/subtask&gt;
→   &lt;subtask&gt;ed18a2ba-4490-4e6e-bb5b-c2c6f962d25c&lt;/subtask&gt;</content>
```

...and then start GTG, then the task happily opens without causing a traceback when you open it:

![Screenshot from 2020-06-05 00-42-54](https://user-images.githubusercontent.com/479401/83837920-bf82a600-a6c5-11ea-957c-a9fb3118623a.png)

However, as soon as you close that task editor window, it will corrupt itself again in the same fashion.

The only way to not have the problem is to not have the tag starting the title of that first subtask. So instead of that other task looking like this:

```
	<task id="47@1" status="Active" uuid="fe0dac3f-4607-441e-8fb9-6285401d8cbb" tags="@travels,@friends,@phone">
		<title>@phone Björk to agree on a meeting</title>
```

It must now look like this:

```
	<task id="47@1" status="Active" uuid="fe0dac3f-4607-441e-8fb9-6285401d8cbb" tags="@travels,@friends,@phone">
		<title>phone Björk to agree on a meeting</title>
```

...which, combined with the repaired parent task like previously, will prevent the corruption from happening in the parent task.

I'm wondering if it has anything to do with the fact that this task was the first in the list right after the description...

Anyway, with these detailed instructions, I think that someone smarter than me could probably find the way to solve this bug :)

**Comment by diegogangl** [comment] 2020-06-05 11:59
This is already fixed in the new taskview widget since we go on a loop line-by-line and don't add additional tags when a line has a subtask. Therefore there are no nested text tags (except for the checkbox maybe). So this bug can't happen anymore

**Comment by nekohayo** [comment] 2020-06-05 13:23
Oh great I didn't know you already had a fix pending! Then that'll be something to close when that branch lands. Also if you branch has automated tests, this is definitely something that would benefit from having one, because it took years to troubleshoot and narrow down what was causing this nonsense :)

**Closed** 2020-10-17 01:01 UTC
Labels: bug, priority:critical, reproducible-in-git
