### ISSUE TITLE
Cannot edit a recurring task , literally.

### ISSUE THREAD

**Issue by ndcast** [getting-things-gnome/gtg#972] opened 2023-04-20 15:55 UTC
**Context:** Global generic exception

```python-traceback
Traceback (most recent call last):
  File "/snap/getting-things-gnome/7/usr/lib/python3/dist-packages/GTG/gtk/application.py", line 350, in edit_task
    self.browser.on_edit_active_task()
  File "/snap/getting-things-gnome/7/usr/lib/python3/dist-packages/GTG/gtk/browser/main_window.py", line 1059, in on_edit_active_task
    self.app.open_task(tid)
  File "/snap/getting-things-gnome/7/usr/lib/python3/dist-packages/GTG/gtk/application.py", line 553, in open_task
    editor = TaskEditor(requester=self.req, app=self, task=task,
  File "/snap/getting-things-gnome/7/usr/lib/python3/dist-packages/GTG/gtk/editor/editor.py", line 98, in __init__
    self.recurring_menu = RecurringMenu(self.req, task.tid, self.builder)
  File "/snap/getting-things-gnome/7/usr/lib/python3/dist-packages/GTG/gtk/editor/recurring_menu.py", line 45, in __init__
    self.update_header()
  File "/snap/getting-things-gnome/7/usr/lib/python3/dist-packages/GTG/gtk/editor/recurring_menu.py", line 121, in update_header
    month_day=self.task.get_recurring_updated_date().strftime('%d')))
AttributeError: 'Date' object has no attribute 'strftime'
```

**Software versions:**
* Getting Things GNOME! v0.6-20-g55a1a624-dirty
* CPython 3.8.10 (default, Nov 14 2022, 12:59:47)   [GCC 9.4.0]
* GTK 3.24.38, GLib 2.64.6
* PyGLib 3.36.2, PyGObject 3.36.2
* Linux-5.19.0-40-generic-x86_64-with-glibc2.29

**Comment by azmeuk** [comment] 2023-05-10 15:05
Looks like a duplicate of #870

**Comment by nekohayo** [comment] 2023-05-10 19:30
Indeed, duplicate of #870

**Closed by nekohayo** 2023-05-10 19:30 UTC
Labels: recurrence
