### ISSUE TITLE
Task editor windows open on the "wrong" monitor (aka figure out what to do about the ability to position windows)

### ISSUE THREAD

**Issue by rustjori** [getting-things-gnome/gtg#688] opened 2021-07-11 03:29 UTC
I would like GTG to open every new windows in the Current Monitor.

Right now my new windows insist on opening in the laptop's own screen, even when i am on either of two external monitors. One of them is even designated as the Primary Monitor.

Suggestion: open new windows where the Mouse is. 
If that is too hard, then in the monitor where GTG Main window is.

-----
georg@delli ~$ inxi -G
Graphics:  Device-1: Intel 3rd Gen Core processor Graphics driver: i915 v: kernel 
           Device-2: NVIDIA GK107GLM [Quadro K1000M] driver: nvidia v: 390.143 
           Display: x11 server: X.Org 1.20.9 driver: modesetting,nvidia 
           unloaded: fbdev,nouveau,vesa 
           resolution: 1920x1080~60Hz, 1920x1080~60Hz, 1920x1080~60Hz 
           OpenGL: renderer: Quadro K1000M/PCIe/SSE2 v: 4.6.0 NVIDIA 390.143 
georg@delli ~$ inxi -S
System:    Host: delli Kernel: 5.4.0-58-generic x86_64 bits: 64 Desktop: Cinnamon 4.8.6 
           Distro: Linux Mint 20.1 Ulyssa 

GTG is version 0.5, which I today downloaded with Software Manager.

**Comment by nekohayo** [comment] 2021-07-11 18:28
The problem is that it will be impossible for applications to move their windows themselves in Wayland: https://gitlab.gnome.org/GNOME/mutter/-/issues/669#note_549129

Apparently they want to design [a different solution](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/18) where applications are allowed to save and restore "sessions"... but I'm not sure what this means for GTG, and for the issue you have reported here, in practice...

**Comment by Neui** [comment] 2021-07-12 19:16
They're on X11, so this isn't really a problem for now. Also, it seems according to [the code](https://github.com/getting-things-gnome/gtg/blob/e4b148b6b31bd563737bb3516d0e30a1d7551369/GTG/gtk/editor/editor.py#L399-L403) it only use the ["first" monitor](https://developer.gnome.org/gdk3/stable/GdkDisplay.html#gdk-display-get-monitor). If we would correctly "fix" it, then we would need to consider all monitors and look at some edge cases (the "combined" valid space isn't a rectangle but can have some "blind" spots). AFAIK the Gnome DE fixes offscreen windows on their own, it was primarily for me using i3-wm which doesn't clamp the windows.

**Comment by nekohayo** [comment] 2021-08-17 16:46
Actually, essentially a duplicate of issue #631 ?

**Comment by nekohayo** [comment] 2022-05-31 00:13
Retitled 631 for clarity, and considering this a duplicate of it.

**Closed by nekohayo** 2022-05-31 00:13 UTC
Labels: needinfo, patch-or-wont-happen
