### ISSUE TITLE
"Add parent" broken, deletes original task and children

### ISSUE THREAD

**Issue by GurvanKervern** [getting-things-gnome/gtg#543] opened 2021-01-20 14:17 UTC
Same version (Github version on Ubuntu 20.04, start with ./launch.sh -d), "add parent" creates a parent task but deletes the original task and its children

**Comment by nekohayo** [comment] 2021-01-20 15:25
Uh, isn't this the exact same bug report as #542 (except that 543 has a clearer title)?

**Comment by zeddo123** [comment] 2021-01-20 15:26
Hi,
I was not able to reproduce the bug.

Are you using the "add parent" in the task editor or the context menu (right click with mouse)?

**Comment by nekohayo** [comment] 2021-01-20 15:30
Let's close this in favor of 542 and continue the investigation there :)

**Closed by nekohayo** 2021-01-20 15:30 UTC
Labels: bug, duplicate, needinfo

**Comment by GurvanKervern** [comment] 2021-01-20 17:36
Well I thought it was different as I understood why maybe "add parent" would recreate a task with a new id but the same content, title, etc, and delete the old "duplicate". But there is the fact the original task and its children are deleted.

Another one is that this behavior is apparently also applied to "open parent" when the title would suggest a different behavior. But I can continue in 542, no worry :)

**Comment by GurvanKervern** [comment] 2021-01-20 17:54
> Hi,
> I was not able to reproduce the bug.
> 
> Are you using the "add parent" in the task editor or the context menu (right click with mouse)?

Sorry, I'll reply here in case you're not notified for the other issue :)

All those things I mentioned were in the task editor, opened with Ctrl+Enter or Ctrl+e.
