### ISSUE TITLE
Fatal internal error - GTG

### ISSUE THREAD

**Issue by CarM-GVA** [getting-things-gnome/gtg#893] opened 2022-05-09 16:26 UTC
First of all, I want to thank you for your work. 

Recently, I have seen a "Fatal internal error - GTG". I do not have technical knowledge, so I cannot provide you with a lot of information. Here you have the details provided by the app:

```
**Context:** Activation
```python-traceback
None```

**Software versions:**
* Getting Things GNOME! v0.6
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.3.0]
* GTK 3.24.33, GLib 2.72.1
* PyGLib 3.42.1, PyGObject 3.42.1
* Linux-5.17.5-200.fc35.x86_64-x86_64-with-glibc2.33
```
I am running the Flatpak version with Fedora 35.

**Comment by WanderningMaster** [comment] 2022-05-10 11:45
Same problem

**Comment by diegogangl** [comment] 2022-05-13 01:06
Hey guys, sorry to hear about this. Weird that it's not generating a traceback. Can you run gtg from a terminal and paste what comes out?

`flatpak run org.gnome.GTG -d`

**Comment by CarM-GVA** [comment] 2022-05-13 08:20
Hey, diegogangl. Thanks for your attention. I ran that code through the terminal. Here you have the output:

`2022-05-13 10:18:40,446 - DEBUG - application:set_logging:669 - Debug output enabled.
2022-05-13 10:18:40,460 - DEBUG - __init__:__init__:60 - Backends found: ['backend_caldav', 'backend_localfile', 'backend_signals']
2022-05-13 10:18:40,633 - DEBUG - xml:open_file:215 - Opening file /home/carlosm/.var/app/org.gnome.GTG/data/gtg/gtg_data.xml
2022-05-13 10:18:40,636 - DEBUG - task:add_child:678 - adding child 0653765c-f5d4-4b7f-9903-0065bb258940 to task 33d9760d-2e07-4ae4-9c02-1fcdaeb46325
2022-05-13 10:18:40,636 - DEBUG - task:add_child:678 - adding child 3efd01b7-343d-4be1-9bac-8ed944517e3f to task 33d9760d-2e07-4ae4-9c02-1fcdaeb46325
2022-05-13 10:18:40,636 - DEBUG - task:add_child:678 - adding child 9b05a6c5-81e3-4fe5-a70d-3b569f65409c to task 33d9760d-2e07-4ae4-9c02-1fcdaeb46325
2022-05-13 10:18:40,636 - DEBUG - task:add_child:678 - adding child 21ed54a8-e7ff-408a-b648-8d12cc75e162 to task 33d9760d-2e07-4ae4-9c02-1fcdaeb46325
2022-05-13 10:18:40,636 - DEBUG - task:add_child:678 - adding child d1c73224-9eec-4889-b3c4-bb0281e5c1d3 to task 33d9760d-2e07-4ae4-9c02-1fcdaeb46325
2022-05-13 10:18:40,636 - DEBUG - task:add_child:678 - adding child 586dd1a7-0772-4d0a-85db-34edfc8ee30c to task 33d9760d-2e07-4ae4-9c02-1fcdaeb46325
2022-05-13 10:18:40,638 - DEBUG - task:add_child:678 - adding child f140cb14-c4c3-40ab-9578-a9f676420955 to task eff27fda-71d5-47c5-bea0-9ef84ba0320b
2022-05-13 10:18:40,646 - DEBUG - task:add_child:678 - adding child 540e3b05-178b-4f67-9f94-fbf60b960bfd to task 24cfa481-094e-4377-8d1f-37c58341ec46
2022-05-13 10:18:40,646 - DEBUG - task:add_child:678 - adding child a0d38bd7-34d5-4f58-8f00-f4e6d9d5833b to task 24cfa481-094e-4377-8d1f-37c58341ec46
2022-05-13 10:18:40,647 - DEBUG - task:add_child:678 - adding child 736ea6d3-cae4-484c-800d-5c96c000130b to task 728d743d-8521-4b80-afe5-c9f6a8c13d70
2022-05-13 10:18:40,647 - DEBUG - task:add_child:678 - adding child 3488563d-6e23-433e-91cf-29bed845ecd3 to task 728d743d-8521-4b80-afe5-c9f6a8c13d70
2022-05-13 10:18:40,647 - DEBUG - task:add_child:678 - adding child 7a5d99b2-f1ba-4401-b49e-fef5fa1afef7 to task 728d743d-8521-4b80-afe5-c9f6a8c13d70
2022-05-13 10:18:40,647 - DEBUG - task:add_child:678 - adding child 322b7091-c4cc-4e6d-b1af-72d467b6aaac to task 728d743d-8521-4b80-afe5-c9f6a8c13d70
2022-05-13 10:18:40,647 - DEBUG - task:add_child:678 - adding child 19920dbd-61fd-45a8-8382-0a60de22b1ef to task 728d743d-8521-4b80-afe5-c9f6a8c13d70
2022-05-13 10:18:40,647 - DEBUG - task:add_child:678 - adding child eed97397-4b34-487b-86aa-709c2ca0e8ff to task 728d743d-8521-4b80-afe5-c9f6a8c13d70
2022-05-13 10:18:40,754 - DEBUG - adaptive_button:do_add:253 - widget=<Gtk.Label object at 0x7fa4137f8280 (GtkLabel at 0x55659d9f2690)>
2022-05-13 10:18:40,754 - DEBUG - adaptive_button:do_add:253 - widget=<Gtk.Image object at 0x7fa4137f1480 (GtkImage at 0x55659da20b50)>
2022-05-13 10:18:40,791 - ERROR - application:do_activate:153 - Exception during activation
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: org.freedesktop.DBus.Error.NameHasNoOwner

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 148, in do_activate
    self.init_shared()
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 229, in init_shared
    self.init_plugin_engine()
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 255, in init_plugin_engine
    self.plugin_engine.activate_plugins()
  File "/app/lib/python3.9/site-packages/GTG/core/plugins/engine.py", line 202, in activate_plugins
    plugin.instance.activate(api)
  File "/app/lib/python3.9/site-packages/GTG/plugins/hamster/hamster.py", line 155, in activate
    self.hamster = dbus.SessionBus().get_object('org.gnome.Hamster',
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/app/lib/python3.9/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/app/lib/python3.9/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/app/lib/python3.9/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
2022-05-13 10:19:06,374 - DEBUG - errorhandler:handle_response:161 - handling response 1
2022-05-13 10:19:06,374 - INFO - errorhandler:handle_response:163 - Going to exit because either of fatal error or user choice`

**Comment by Neui** [comment] 2022-05-13 08:52
Looks like a duplicate of #683. You unfortunately need to disable the hamster plugin, see https://github.com/getting-things-gnome/gtg/issues/770#issuecomment-1030678522 for how to do that:

> Try this: Open `${XDG_CONFIG_HOME:-$HOME/.config}/gtg/gtg.conf` (or `~/.var/app/org.gnome.GTG/config/gtg/gtg.conf` when using the flatpak version, or `tmp/default/xdg/config/gtg/gtg.conf` when using `./launch.sh`) in an plain text editor, and find `[plugins]`, and under it remove `hamster` from `enabled =` (possibly with a comma if you had enabled multiple plugins), start GTG. Make sure GTG is closed (no process running).

**Comment by nekohayo** [comment] 2022-05-23 22:23
We'll presume it is a duplicate of that issue unless you are still experiencing it after doing the workaround, in which case this ticket could be reopened.

**Closed by nekohayo** 2022-05-23 22:23 UTC
Labels: duplicate

**Comment by LuigiWriter** [comment] 2022-07-04 18:45
Same error, However,  hamster is not listed in enabled =
enabled = untouched_tasks,urgency_color
disabled = export,send_email
This problem just cropped up 2022-07-02

**Comment by LuigiWriter** [comment] 2022-07-04 19:00
Here is result of running
luigiwriter@luigi_Envy14:~/.var/app/org.gnome.GTG/config/gtg$ flatpak run org.gnome.GTG -d
2022-07-04 14:54:49,054 - DEBUG - application:set_logging:669 - Debug output enabled.
Gtk-Message: 14:54:49.110: Failed to load module "canberra-gtk-module"
2022-07-04 14:54:49,115 - DEBUG - __init__:__init__:60 - Backends found: ['backend_localfile', 'backend_caldav', 'backend_signals']
2022-07-04 14:54:49,638 - DEBUG - xml:open_file:215 - Opening file /home/luigiwriter/.var/app/org.gnome.GTG/data/gtg/gtg_data.xml
2022-07-04 14:54:49,666 - DEBUG - task:add_child:678 - adding child 58d1ce8c-a006-495d-a408-615db2022ee2 to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,666 - DEBUG - task:add_child:678 - adding child b4bdd21b-a801-4e81-acd5-2faf153eb032 to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,666 - DEBUG - task:add_child:678 - adding child dd0b8c59-778a-4b8c-9b1c-668ea1e74c7c to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,666 - DEBUG - task:add_child:678 - adding child 3d637cdc-73f2-4b92-8cf3-e81b18a613cb to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,667 - DEBUG - task:add_child:678 - adding child bfe3572e-268b-46ee-9bc0-ffcd3136b033 to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,667 - DEBUG - task:add_child:678 - adding child ad28e098-90e6-49cd-9b85-70aa237e6975 to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,667 - DEBUG - task:add_child:678 - adding child 1e969d57-6ac3-4b90-85a7-2aa00d146bff to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,667 - DEBUG - task:add_child:678 - adding child 22198eae-e104-455f-b93b-3eb59500f54f to task 41489cb1-0910-446c-94fe-85a72d509ad3
2022-07-04 14:54:49,669 - DEBUG - task:add_child:678 - adding child 179398d3-7a1d-4245-8605-d9591fa13a75 to task 58d1ce8c-a006-495d-a408-615db2022ee2
2022-07-04 14:54:49,698 - DEBUG - task:add_child:678 - adding child 7de19fce-7862-43a9-bf25-09f26cdac074 to task 66667ee0-4a20-4f39-af7a-a2bc023abeee
2022-07-04 14:54:49,698 - DEBUG - task:add_child:678 - adding child e54871f9-d0ec-4004-8ff8-f550974a1eff to task 66667ee0-4a20-4f39-af7a-a2bc023abeee
2022-07-04 14:54:49,699 - DEBUG - task:add_child:678 - adding child f6184319-3b4c-4027-a52d-6c2b1f025eb1 to task 66667ee0-4a20-4f39-af7a-a2bc023abeee
2022-07-04 14:54:49,699 - DEBUG - task:add_child:678 - adding child 9f694ffb-de0f-4e49-8d70-5c1288ab9eb9 to task 66667ee0-4a20-4f39-af7a-a2bc023abeee
2022-07-04 14:54:49,699 - DEBUG - task:add_child:678 - adding child 3fc93eca-e480-4bc1-9340-ce9225184b75 to task 66667ee0-4a20-4f39-af7a-a2bc023abeee
2022-07-04 14:54:49,699 - DEBUG - task:add_child:678 - adding child f87d61b9-30ad-43d3-ac08-3ed389fdf5c0 to task 66667ee0-4a20-4f39-af7a-a2bc023abeee
2022-07-04 14:54:49,714 - DEBUG - task:add_child:678 - adding child 0ffda5ec-550c-4d81-b96d-106e81f2c1ca to task f591c727-2127-463b-80a5-c461e5d6d705
2022-07-04 14:54:49,714 - DEBUG - task:add_child:678 - adding child 2658c68b-1282-452c-850e-a84f5d0e00e5 to task f591c727-2127-463b-80a5-c461e5d6d705
2022-07-04 14:54:49,714 - DEBUG - task:add_child:678 - adding child 276d7a73-05c0-4bf0-85ce-8bfea5bf7eb4 to task f591c727-2127-463b-80a5-c461e5d6d705
2022-07-04 14:54:49,714 - DEBUG - task:add_child:678 - adding child 4e3b7d2c-495d-45fa-bbb7-6ba07b4eb609 to task f591c727-2127-463b-80a5-c461e5d6d705
2022-07-04 14:54:49,714 - DEBUG - task:add_child:678 - adding child c3656665-003e-4b9c-b6fc-6f8b135ce8a1 to task f591c727-2127-463b-80a5-c461e5d6d705
2022-07-04 14:54:49,715 - DEBUG - task:add_child:678 - adding child a4fde0c8-88a4-4389-b4ca-9766eb0a2464 to task f591c727-2127-463b-80a5-c461e5d6d705
2022-07-04 14:54:49,735 - DEBUG - task:add_child:678 - adding child 44fffaad-25c4-4dad-8f84-32de89a07ffa to task c3656665-003e-4b9c-b6fc-6f8b135ce8a1
2022-07-04 14:54:49,750 - DEBUG - task:add_child:678 - adding child 40367aa7-49ae-45a5-a4e6-745f437207bd to task 60c74d6c-5b1c-49a4-bfaa-cc60fe3728f1
2022-07-04 14:54:49,750 - DEBUG - task:add_child:678 - adding child 57d8ac82-a296-47d4-a258-a21886bc98e7 to task 60c74d6c-5b1c-49a4-bfaa-cc60fe3728f1
2022-07-04 14:54:49,751 - DEBUG - task:add_child:678 - adding child b9691b2f-37b5-485b-a742-78a3dfb021f3 to task 60c74d6c-5b1c-49a4-bfaa-cc60fe3728f1
2022-07-04 14:54:49,751 - DEBUG - task:add_child:678 - adding child 0abd2e7a-6bed-4b36-86a6-24c7c2992c72 to task 60c74d6c-5b1c-49a4-bfaa-cc60fe3728f1
2022-07-04 14:54:49,751 - DEBUG - task:add_child:678 - adding child e699394f-077c-4576-8639-5678c62aee28 to task 60c74d6c-5b1c-49a4-bfaa-cc60fe3728f1
2022-07-04 14:54:49,751 - DEBUG - task:add_child:678 - adding child 43269628-74be-4bfb-b856-0598aec7f734 to task 60c74d6c-5b1c-49a4-bfaa-cc60fe3728f1
2022-07-04 14:54:49,792 - DEBUG - task:add_child:678 - adding child 7af4ec05-c310-4b8c-aaeb-ebf7ca6a686e to task 502e50f1-2ec4-47d4-a2fd-f0e422281ea8
2022-07-04 14:54:49,793 - DEBUG - task:add_child:678 - adding child 01c4256c-5caf-4bfa-bdb0-c176abc62507 to task 502e50f1-2ec4-47d4-a2fd-f0e422281ea8
2022-07-04 14:54:49,793 - DEBUG - task:add_child:678 - adding child fbf61efa-2ae1-4009-9042-a1fc2d65aca9 to task 502e50f1-2ec4-47d4-a2fd-f0e422281ea8
2022-07-04 14:54:49,795 - DEBUG - task:add_child:678 - adding child 9801b896-af53-43d5-abe2-00a4fc2bdab6 to task c427cda9-e3d2-4922-ac32-41f711e2b39f
2022-07-04 14:54:49,798 - DEBUG - task:add_child:678 - adding child c427cda9-e3d2-4922-ac32-41f711e2b39f to task 15f2ed36-a99d-4c33-ab66-2478e604a50d
2022-07-04 14:54:49,799 - DEBUG - task:add_child:678 - adding child 986b8544-f46c-4e63-9a52-feb68bc3b7d1 to task 15f2ed36-a99d-4c33-ab66-2478e604a50d
2022-07-04 14:54:49,799 - DEBUG - task:add_child:678 - adding child 0fe9f1aa-8258-4dbd-ab24-6ae3146d7146 to task 15f2ed36-a99d-4c33-ab66-2478e604a50d
2022-07-04 14:54:49,799 - DEBUG - task:add_child:678 - adding child 4d9e98c8-d7b5-415c-8e98-7c3438f72c3b to task 15f2ed36-a99d-4c33-ab66-2478e604a50d
2022-07-04 14:54:49,822 - DEBUG - task:add_child:678 - adding child a0786844-fff9-4fef-b50d-0ef9165adb7f to task f34e995e-2e74-4cea-ba1c-84e2a27da86d
2022-07-04 14:54:49,822 - DEBUG - task:add_child:678 - adding child 12fdad07-c7e7-4638-b294-6509f4131b3a to task f34e995e-2e74-4cea-ba1c-84e2a27da86d
2022-07-04 14:54:49,822 - DEBUG - task:add_child:678 - adding child 74f3c76b-3e14-4058-a299-b347f5b6b768 to task f34e995e-2e74-4cea-ba1c-84e2a27da86d
2022-07-04 14:54:49,822 - DEBUG - task:add_child:678 - adding child f58ee939-b6e8-464a-8a34-0911fad443ee to task f34e995e-2e74-4cea-ba1c-84e2a27da86d
2022-07-04 14:54:49,886 - DEBUG - task:add_child:678 - adding child 103bda14-4cfd-4ac8-9bc1-793b8e4b90d0 to task 68e4536a-d166-40b3-9316-ddd0a88207a6
2022-07-04 14:54:49,886 - DEBUG - task:add_child:678 - adding child 54224fcc-e4da-496d-b1d4-68e93127845c to task 68e4536a-d166-40b3-9316-ddd0a88207a6
2022-07-04 14:54:49,886 - DEBUG - task:add_child:678 - adding child 5b68ad82-34c7-46be-837c-abf7e7e3dea0 to task 68e4536a-d166-40b3-9316-ddd0a88207a6
2022-07-04 14:54:49,886 - DEBUG - task:add_child:678 - adding child f2f9fb7b-05c7-4ab5-a1ed-34d259b891c0 to task 68e4536a-d166-40b3-9316-ddd0a88207a6
2022-07-04 14:54:49,929 - DEBUG - task:add_child:678 - adding child af4644f3-21f5-47f9-8cd3-bff837e5b703 to task 103bda14-4cfd-4ac8-9bc1-793b8e4b90d0
2022-07-04 14:54:49,947 - DEBUG - task:add_child:678 - adding child ee92af88-535d-4b79-9149-0508255a63b8 to task 12fdad07-c7e7-4638-b294-6509f4131b3a
2022-07-04 14:54:49,947 - DEBUG - task:add_child:678 - adding child 14ae3d02-bce1-4bee-aeed-b5d088b8d84e to task 12fdad07-c7e7-4638-b294-6509f4131b3a
2022-07-04 14:54:49,947 - DEBUG - task:add_child:678 - adding child 5cb19136-0104-4f41-b9a4-7c8f2720e22f to task 12fdad07-c7e7-4638-b294-6509f4131b3a
2022-07-04 14:54:49,947 - DEBUG - task:add_child:678 - adding child 7c544480-3a80-4760-92aa-824624d765c8 to task 12fdad07-c7e7-4638-b294-6509f4131b3a
2022-07-04 14:54:49,947 - DEBUG - task:add_child:678 - adding child b51a837c-d79f-455b-b54f-ca18c73b3867 to task 12fdad07-c7e7-4638-b294-6509f4131b3a
2022-07-04 14:54:49,975 - DEBUG - task:add_child:678 - adding child 56626b44-052e-4cc6-ae0b-3177033def39 to task 83691d27-990d-46df-9ef4-fe451907d587
2022-07-04 14:54:50,002 - DEBUG - task:add_child:678 - adding child dc4eb8f2-c2db-4537-aac4-e7be3dfb7964 to task f58ee939-b6e8-464a-8a34-0911fad443ee
2022-07-04 14:54:50,002 - DEBUG - task:add_child:678 - adding child 622a3893-3b6e-489e-a5f1-f89ce35d4463 to task f58ee939-b6e8-464a-8a34-0911fad443ee
2022-07-04 14:54:50,002 - DEBUG - task:add_child:678 - adding child 3e3ba47b-211e-4c08-9c03-ebf4201bb8f8 to task f58ee939-b6e8-464a-8a34-0911fad443ee
2022-07-04 14:54:50,002 - DEBUG - task:add_child:678 - adding child ad826779-bf13-4073-8667-6121c82b21c3 to task f58ee939-b6e8-464a-8a34-0911fad443ee
2022-07-04 14:54:50,002 - DEBUG - task:add_child:678 - adding child 73421438-add5-4063-9638-2dceb2eae4bc to task f58ee939-b6e8-464a-8a34-0911fad443ee
2022-07-04 14:54:50,014 - DEBUG - task:add_child:678 - adding child 495cc797-8ea0-4e0c-8640-e29f100a8cc3 to task 1f34ad34-b2d4-4c9d-84c5-ec1aa98a6bfe
2022-07-04 14:54:50,015 - DEBUG - task:add_child:678 - adding child d38e25a1-5ab0-49b6-9abb-5280c6780310 to task 1f34ad34-b2d4-4c9d-84c5-ec1aa98a6bfe
2022-07-04 14:54:50,015 - DEBUG - task:add_child:678 - adding child 62997a6a-3e96-4724-98e2-37931eafa836 to task 1f34ad34-b2d4-4c9d-84c5-ec1aa98a6bfe
2022-07-04 14:54:50,015 - DEBUG - task:add_child:678 - adding child cb9b3a6d-325d-4a95-be69-dbff32bbd2f7 to task 1f34ad34-b2d4-4c9d-84c5-ec1aa98a6bfe
2022-07-04 14:54:50,015 - DEBUG - task:add_child:678 - adding child 8537ce5b-9d8d-4f63-bb02-72bf5cf5be21 to task 1f34ad34-b2d4-4c9d-84c5-ec1aa98a6bfe
2022-07-04 14:54:50,015 - DEBUG - task:add_child:678 - adding child 0f6c07f7-b0ef-4732-8b77-cb6638a229c2 to task 1f34ad34-b2d4-4c9d-84c5-ec1aa98a6bfe
2022-07-04 14:54:50,104 - DEBUG - task:add_child:678 - adding child 3f3f017f-4d74-429a-ad93-ba59c64bdd47 to task 5b16f3d0-4d69-41cc-ae27-cfef86971e54
2022-07-04 14:54:50,158 - DEBUG - task:add_child:678 - adding child 0be32446-a3fe-445c-968a-428c62d9a312 to task 5841651f-6957-4050-aecd-5c92a7fb797d
2022-07-04 14:54:50,160 - DEBUG - task:add_child:678 - adding child a9681098-b907-4518-bfaf-9de04774262e to task fa35d7b3-017d-475c-aab7-d450b0f9bac8
2022-07-04 14:54:50,208 - DEBUG - task:add_child:678 - adding child 44b392db-82af-47b1-b992-8f552a758c39 to task 9b56396c-2e1f-450b-aa33-de784ca82976
2022-07-04 14:54:50,208 - DEBUG - task:add_child:678 - adding child f3bad687-bfd6-4f5d-a219-a72e9e7998c3 to task 9b56396c-2e1f-450b-aa33-de784ca82976
2022-07-04 14:54:50,208 - DEBUG - task:add_child:678 - adding child 66792881-53dd-4272-a34d-b0bfc8486bab to task 9b56396c-2e1f-450b-aa33-de784ca82976
2022-07-04 14:54:50,208 - DEBUG - task:add_child:678 - adding child c5486366-49ee-400c-a79c-f61741cd84c6 to task 9b56396c-2e1f-450b-aa33-de784ca82976
2022-07-04 14:54:50,209 - DEBUG - task:add_child:678 - adding child 82a0c852-f517-41af-aa3c-2ec1b94196ee to task 9b56396c-2e1f-450b-aa33-de784ca82976
2022-07-04 14:54:50,209 - DEBUG - task:add_child:678 - adding child ec8fb13d-7f35-45ca-a0cd-1912ac1f3988 to task 9b56396c-2e1f-450b-aa33-de784ca82976
2022-07-04 14:54:50,209 - DEBUG - task:add_child:678 - adding child 74323f4f-6357-455a-820e-83a9346f75df to task 9b56396c-2e1f-450b-aa33-de784ca82976
2022-07-04 14:54:51,129 - DEBUG - adaptive_button:do_add:253 - widget=<Gtk.Label object at 0x7f4af89e9900 (GtkLabel at 0x55aab4ac53f0)>
2022-07-04 14:54:51,130 - DEBUG - adaptive_button:do_add:253 - widget=<Gtk.Image object at 0x7f4af89e5a00 (GtkImage at 0x55aab4af4b50)>
2022-07-04 14:54:53,110 - DEBUG - untouchedTasks:add_untouched_tag:105 - Starting process for adding @untouched
2022-07-04 14:54:53,130 - ERROR - application:do_activate:153 - Exception during activation
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 148, in do_activate
    self.init_shared()
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 229, in init_shared
    self.init_plugin_engine()
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 255, in init_plugin_engine
    self.plugin_engine.activate_plugins()
  File "/app/lib/python3.9/site-packages/GTG/core/plugins/engine.py", line 202, in activate_plugins
    plugin.instance.activate(api)
  File "/app/lib/python3.9/site-packages/GTG/plugins/untouched_tasks/untouchedTasks.py", line 72, in activate
    self.preferences_apply()
  File "/app/lib/python3.9/site-packages/GTG/plugins/untouched_tasks/untouchedTasks.py", line 173, in preferences_apply
    self.add_untouched_tag()
  File "/app/lib/python3.9/site-packages/GTG/plugins/untouched_tasks/untouchedTasks.py", line 117, in add_untouched_tag
    if new_time < today:
TypeError: can't compare datetime.datetime to datetime.date
2022-07-04 14:55:05,409 - DEBUG - errorhandler:handle_response:161 - handling response 1
2022-07-04 14:55:05,410 - INFO - errorhandler:handle_response:163 - Going to exit because either of fatal error or user choice

Given the duplicate tag If someone can let me know which # of several it is or was a duplicate, I will be glad to append these comments to it.
Or should I open a new issue
